IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'vwx_UnFlattenedPOMS')
   BEGIN
            DROP VIEW vwx_UnFlattenedPOMS
   END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'vwx_sizerange1')
   BEGIN
            DROP VIEW vwx_sizerange1
   END
GO
