
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0004', N'zh-CNS', N'Chinese (Simplified)', N'Chinese', 1, 1)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0406', N'da-DK', N'Denmark', N'Danish', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0407', N'de-DE', N'Germany', N'German', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0409', N'en-US', N'United States', N'English', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x040C', N'fr-FR', N'France', N'French', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0410', N'it-IT', N'Italy', N'Italian', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0411', N'ja-JA', N'Japan', N'Japanese', 1, 1)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0412', N'ko-KR', N'Korean', N'Korean', 1, 1)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0413', N'nl_NL', N'The Netherlands', N'Dutch', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0415', N'pl_PL', N'Poland', N'Polish', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0416', N'pt-BR', N'Brazil', N'Portuguese', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0419', N'ru-RU', N'Russia', N'Russian', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x041D', N'sv-SE', N'Sweden', N'Swedish', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x041F', N'tr-TR', N'Turkey', N'Turkish', 1, 1)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0439', N'hi-IN', N'India', N'Hindi', 1, 1)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0809', N'en-GB', N'United Kingdom', N'English', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x080A', N'es-MX', N'Mexico', N'Spanish', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0816', N'pt-PT', N'Portugal', N'Portuguese', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x081D', N'sv-FI', N'Finland', N'Swedish', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0C0A', N'es-ES', N'Spain', N'Spanish', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x0C0C', N'fr-CA', N'Canada', N'French', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x1009', N'en-CA', N'Canada', N'English', 1, 0)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0x7C04', N'zh-CHT', N'Chinese (Traditional)', N'Chinese', 1, 1)
INSERT [dbo].[sSystemCulture] ([CultureIndentifierID], [CultureName], [CultureCountry], [CultureLanguage], [Active], [Unicode]) VALUES (N'0xtttt', N'TstLng', N'', N'TestLang', 1, 0)


INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES     ('DB_Version', '4.0.0.0', '594', GetDate())
GO 