IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalHeader' and COLUMN_NAME = N'CUser')
       BEGIN 
             ALTER TABLE pMSEvalHeader ADD CUser nvarchar(200) NULL
       END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalHeader' and COLUMN_NAME = N'CDate')
       BEGIN 
             ALTER TABLE pMSEvalHeader ADD CDate datetime NULL
       END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalHeader' and COLUMN_NAME = N'MUser')
       BEGIN 
             ALTER TABLE pMSEvalHeader ADD MUser nvarchar(200) NULL
       END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalHeader' and COLUMN_NAME = N'MDate')
       BEGIN 
             ALTER TABLE pMSEvalHeader ADD MDate datetime NULL
       END
GO



IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalPom' and COLUMN_NAME = N'CUser')
       BEGIN 
             ALTER TABLE pMSEvalPom ADD CUser nvarchar(200) NULL
       END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalPom' and COLUMN_NAME = N'CDate')
       BEGIN 
             ALTER TABLE pMSEvalPom ADD CDate datetime NULL
       END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalPom' and COLUMN_NAME = N'MUser')
       BEGIN 
             ALTER TABLE pMSEvalPom ADD MUser nvarchar(200) NULL
       END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalPom' and COLUMN_NAME = N'MDate')
       BEGIN 
             ALTER TABLE pMSEvalPom ADD MDate datetime NULL
       END
GO



IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalSampLbl' and COLUMN_NAME = N'CUser')
       BEGIN 
             ALTER TABLE pMSEvalSampLbl ADD CUser nvarchar(200) NULL
       END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalSampLbl' and COLUMN_NAME = N'CDate')
       BEGIN 
             ALTER TABLE pMSEvalSampLbl ADD CDate datetime NULL
       END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalSampLbl' and COLUMN_NAME = N'MUser')
       BEGIN 
             ALTER TABLE pMSEvalSampLbl ADD MUser nvarchar(200) NULL
       END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalSampLbl' and COLUMN_NAME = N'MDate')
       BEGIN 
             ALTER TABLE pMSEvalSampLbl ADD MDate datetime NULL
       END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalSampMeas' and COLUMN_NAME = N'CUser')
       BEGIN 
             ALTER TABLE pMSEvalSampMeas ADD CUser nvarchar(200) NULL
       END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalSampMeas' and COLUMN_NAME = N'CDate')
       BEGIN 
             ALTER TABLE pMSEvalSampMeas ADD CDate datetime NULL
       END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalSampMeas' and COLUMN_NAME = N'MUser')
       BEGIN 
             ALTER TABLE pMSEvalSampMeas ADD MUser nvarchar(200) NULL
       END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pMSEvalSampMeas' and COLUMN_NAME = N'MDate')
       BEGIN 
             ALTER TABLE pMSEvalSampMeas ADD MDate datetime NULL
       END
GO


INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES     ('DB_Version', '4.0.0000', '01031', GetDate())
GO
