UPDATE pSampleWorkflow SET SampleWorkflowSort = '075' WHERE SampleWorkflowID = '01B'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '076' WHERE SampleWorkflowID = '02B'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '077' WHERE SampleWorkflowID = '03B'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '078' WHERE SampleWorkflowID = '04B'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '079' WHERE SampleWorkflowID = '05B'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '080' WHERE SampleWorkflowID = '06B'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '081' WHERE SampleWorkflowID = '07B'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '082' WHERE SampleWorkflowID = '08B'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '083' WHERE SampleWorkflowID = '09B'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '084' WHERE SampleWorkflowID = '10B'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '085' WHERE SampleWorkflowID = '11B'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '086' WHERE SampleWorkflowID = '12B'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '087' WHERE SampleWorkflowID = '13B'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '089' WHERE SampleWorkflowID = '13C'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '090' WHERE SampleWorkflowID = '13D'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '091' WHERE SampleWorkflowID = '13E'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '092' WHERE SampleWorkflowID = '13F'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '093' WHERE SampleWorkflowID = '13G'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '094' WHERE SampleWorkflowID = '13H'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '095' WHERE SampleWorkflowID = '13I'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '096' WHERE SampleWorkflowID = '13J'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '097' WHERE SampleWorkflowID = '13K'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '098' WHERE SampleWorkflowID = '13L'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '099' WHERE SampleWorkflowID = '13M'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '100' WHERE SampleWorkflowID = '13N'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '001' WHERE SampleWorkflowID = '14A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '002' WHERE SampleWorkflowID = '16A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '003' WHERE SampleWorkflowID = '17A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '004' WHERE SampleWorkflowID = '18A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '005' WHERE SampleWorkflowID = '20A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '006' WHERE SampleWorkflowID = '24A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '008' WHERE SampleWorkflowID = '25A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '007' WHERE SampleWorkflowID = '27A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '009' WHERE SampleWorkflowID = '30A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '057' WHERE SampleWorkflowID = '50A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '058' WHERE SampleWorkflowID = '55A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '059' WHERE SampleWorkflowID = '60A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '060' WHERE SampleWorkflowID = '70A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '116' WHERE SampleWorkflowID = '80A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '117' WHERE SampleWorkflowID = '82A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '118' WHERE SampleWorkflowID = '84A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '119' WHERE SampleWorkflowID = '86A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '120' WHERE SampleWorkflowID = '88A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '010' WHERE SampleWorkflowID = '90A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '014' WHERE SampleWorkflowID = '91A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '016' WHERE SampleWorkflowID = '92A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '018' WHERE SampleWorkflowID = '93A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '012' WHERE SampleWorkflowID = '94A'
UPDATE pSampleWorkflow SET SampleWorkflowSort = '020' WHERE SampleWorkflowID = '95A'
GO

IF(NOT EXISTS(SELECT * FROM sVersion WHERE LastScriptRun='02025'))
BEGIN
	
	INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
	VALUES     ('DB_Version', '4.1.0000', '02025', GetDate())     

END	
GO