
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pAMLMeasPOM' and COLUMN_NAME = N'FabricType')
       BEGIN 
			
            ALTER TABLE pAMLMeasPOM ADD FabricType [nvarchar](100) NULL
       END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pAMLMeasPOM' and COLUMN_NAME = N'IsLength')
       BEGIN 
			
            ALTER TABLE pAMLMeasPOM ADD IsLength int NULL
            ALTER TABLE [dbo].[pAMLMeasPOM] ADD  CONSTRAINT [DF_pAMLMeasPOM_IsLength]  DEFAULT ((0)) FOR [IsLength]
       END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pAMLMeasPOM' and COLUMN_NAME = N'IsWidth')
       BEGIN 
			
            ALTER TABLE pAMLMeasPOM ADD IsWidth int NULL
            ALTER TABLE pAMLMeasPOM ADD  CONSTRAINT [DF_pAMLMeasPOM_IsWidth]  DEFAULT ((0)) FOR [IsWidth]
       END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pAMLMeasPOM' and COLUMN_NAME = N'ShrinkX')
       BEGIN 
			ALTER TABLE pAMLMeasPOM ADD ShrinkX numeric(18, 4) NULL

       END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pAMLMeasPOM' and COLUMN_NAME = N'ShrinkY')
       BEGIN 
			
            ALTER TABLE pAMLMeasPOM ADD ShrinkY numeric(18, 4) NULL
       END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pAMLMeasPOM' and COLUMN_NAME = N'CADModelId')
       BEGIN 
			
            ALTER TABLE pAMLMeasPOM ADD CADModelId [nvarchar](100) NULL
       END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pAMLMeasPOM' and COLUMN_NAME = N'BeforeTreat')
       BEGIN 
			
            ALTER TABLE pAMLMeasPOM ADD BeforeTreat numeric(18, 4) NULL

       END
GO

IF(NOT EXISTS(SELECT * FROM sVersion WHERE LastScriptRun='02453'))
BEGIN

	INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
	VALUES     ('DB_Version', '4.1.0000', '02453', GetDate())

END

GO