

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='Active' AND TABLE_NAME='UOM')
BEGIN
	ALTER TABLE UOM ADD [Active] [int] NULL
END  

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='CUser'  AND TABLE_NAME ='UOM')
BEGIN
	ALTER TABLE UOM ADD [CUser]  [nvarchar](50) NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='CDate'  AND TABLE_NAME ='UOM')
BEGIN
	ALTER TABLE UOM ADD [CDate]  [datetime] NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='MUser'  AND TABLE_NAME ='UOM')
BEGIN
	ALTER TABLE UOM ADD [MUser]  [nvarchar](50) NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='MDate'  AND TABLE_NAME ='UOM')
BEGIN
	ALTER TABLE UOM ADD [MDate]  [datetime] NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='UOMSORT'  AND TABLE_NAME ='UOM')
BEGIN
	ALTER TABLE UOM ALTER COLUMN UOMSORT VARCHAR(10)
END

GO

IF(NOT EXISTS(SELECT * FROM sVersion WHERE LastScriptRun='02531'))
BEGIN
	INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
	VALUES     ('DB_Version', '4.2.0000', '02531', GetDate())
END
GO