IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='AvatarImageID' AND TABLE_NAME='Users')
BEGIN
	ALTER TABLE Users ADD AvatarImageID UNIQUEIDENTIFIER NULL
END

IF(NOT EXISTS(SELECT * FROM sVersion WHERE LastScriptRun='03261'))
BEGIN

	INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
	VALUES     ('DB_Version', '5.0.0000', '03261', GetDate())

END
GO