IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='CUser' AND TABLE_NAME='uTradePartnerAddress')
BEGIN
	ALTER TABLE uTradePartnerAddress ADD [CUser] [nvarchar](200) NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='CDate' AND TABLE_NAME='uTradePartnerAddress')
BEGIN
	ALTER TABLE uTradePartnerAddress ADD [CDate] [datetime] NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='MUser' AND TABLE_NAME='uTradePartnerAddress')
BEGIN
	ALTER TABLE uTradePartnerAddress ADD [MUser] [nvarchar](200) NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='MDate' AND TABLE_NAME='uTradePartnerAddress')
BEGIN
	ALTER TABLE uTradePartnerAddress ADD [MDate] [datetime] NULL
END
GO


IF(NOT EXISTS(SELECT * FROM sVersion WHERE LastScriptRun='03281'))
BEGIN

	INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
	VALUES     ('DB_Version', '5.0.0000', '03281', GetDate())

END
GO