IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSeason' and COLUMN_NAME = N'SeasonMonth1')
BEGIN 
	ALTER TABLE pSeason ADD SeasonMonth1 int NULL Default 0
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSeason' and COLUMN_NAME = N'SeasonMonth2')
BEGIN 
	ALTER TABLE pSeason ADD SeasonMonth2 int NULL Default 0
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSeason' and COLUMN_NAME = N'SeasonMonth3')
BEGIN 
	ALTER TABLE pSeason ADD SeasonMonth3 int NULL Default 0
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSeason' and COLUMN_NAME = N'SeasonMonth4')
BEGIN 
	ALTER TABLE pSeason ADD SeasonMonth4 int NULL Default 0
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSeason' and COLUMN_NAME = N'SeasonMonth5')
BEGIN 
	ALTER TABLE pSeason ADD SeasonMonth5 int NULL Default 0
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSeason' and COLUMN_NAME = N'SeasonMonth6')
BEGIN 
	ALTER TABLE pSeason ADD SeasonMonth6 int NULL Default 0
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSeason' and COLUMN_NAME = N'SeasonMonth7')
BEGIN 
	ALTER TABLE pSeason ADD SeasonMonth7 int NULL Default 0
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSeason' and COLUMN_NAME = N'SeasonMonth8')
BEGIN 
	ALTER TABLE pSeason ADD SeasonMonth8 int NULL Default 0
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSeason' and COLUMN_NAME = N'SeasonMonth9')
BEGIN 
	ALTER TABLE pSeason ADD SeasonMonth9 int NULL Default 0
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSeason' and COLUMN_NAME = N'SeasonMonth10')
BEGIN 
	ALTER TABLE pSeason ADD SeasonMonth10 int NULL Default 0
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSeason' and COLUMN_NAME = N'SeasonMonth11')
BEGIN 
	ALTER TABLE pSeason ADD SeasonMonth11 int NULL Default 0
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSeason' and COLUMN_NAME = N'SeasonMonth12')
BEGIN 
	ALTER TABLE pSeason ADD SeasonMonth12 int NULL Default 0
END

GO


IF(NOT EXISTS(SELECT * FROM sVersion WHERE LastScriptRun='03294'))
BEGIN
	INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
	VALUES     ('DB_Version', '5.0.0000', '03294', GetDate())
END
GO