--
-- Change iCustom91 (Fabric Tradename) to NVARCHAR
--
ALTER TABLE iCustom91 ALTER COLUMN CustomKey NVARCHAR(50) NOT NULL
GO
ALTER TABLE iCustom91 ALTER COLUMN Custom NVARCHAR(200) NOT NULL
GO
ALTER TABLE iCustom91 ALTER COLUMN CustomSort NVARCHAR(50) NULL
GO
ALTER TABLE iCustom91 ALTER COLUMN TableRelation NVARCHAR(100) NULL
GO
ALTER TABLE iCustom91 ALTER COLUMN CUser NVARCHAR(200) NULL
GO
ALTER TABLE iCustom91 ALTER COLUMN MUser NVARCHAR(200) NULL
GO
ALTER TABLE iCustom91 ALTER COLUMN TempID NVARCHAR(50) NULL
GO
ALTER TABLE iCustom91 ALTER COLUMN TempNo NVARCHAR(50) NULL
GO

--
-- Change pSeason to NVARCHAR
--
ALTER TABLE pSeason ALTER COLUMN CustomKey NVARCHAR(100) NOT NULL
GO
ALTER TABLE pSeason ALTER COLUMN Custom NVARCHAR(200) NOT NULL
GO
ALTER TABLE pSeason ALTER COLUMN CustomSort NVARCHAR(5) NULL
GO


IF(NOT EXISTS(SELECT * FROM sVersion WHERE LastScriptRun='03306'))
BEGIN

	INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
	VALUES     ('DB_Version', '5.0.0000', '03306', GetDate())

END
GO