IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'UOM' and COLUMN_NAME = N'UOMSort')
BEGIN 
	ALTER TABLE UOM ALTER COLUMN UOMSort VARCHAR(5) NULL
END
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '5.0.0000', '03557', GetDate())
GO