IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pChangeTransaction' and COLUMN_NAME = N'ChangeSessionID')
BEGIN 
	ALTER TABLE pChangeTransaction ADD ChangeSessionID UNIQUEIDENTIFIER NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pChangeTransaction' AND COLUMN_NAME = N'ChangeTransNo')
BEGIN
	ALTER TABLE pChangeTransaction ADD ChangeTransNo BIGINT IDENTITY(1, 1) NOT NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pChangeTransaction' AND COLUMN_NAME = N'ChangeSessionNo')
BEGIN
	ALTER TABLE pChangeTransaction ADD ChangeSessionNo BIGINT NULL
END

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES     ('DB_Version', '5.0.0000', '03701', GetDate())
GO