IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pStyleFeature' and  DATA_TYPE = N'varchar')
BEGIN
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom1 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom2 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom3 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom4 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom5 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom6 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom7 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom8 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom9 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom10 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom11 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom12 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom13 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom14 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom15 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom16 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom17 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom18 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom19 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom20 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom21 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom22 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom23 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom24 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom25 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom26 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom27 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom28 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom29 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom30 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom31 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom32 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom33 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom34 nvarchar(200)
	ALTER TABLE pStyleFeature ALTER COLUMN StyleFeatureCustom35 nvarchar(200)
END
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES     ('DB_Version', '5.0.0000', '03715', GetDate())
GO