IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pChangeLog' AND COLUMN_NAME = 'ChangeTransPageName')
BEGIN
	ALTER TABLE pChangeLog ADD ChangeTransPageName VARCHAR(200) NULL
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pChangeLog' AND COLUMN_NAME = 'ChangeTransTypeID')
BEGIN
	ALTER TABLE pChangeLog ADD ChangeTransTypeID INT NULL
END
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '5.0.0000', '03736', GetDate())
GO