IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pAMLMeasPOM' AND COLUMN_NAME='RefCode')
BEGIN
	ALTER TABLE pAMLMeasPOM ALTER COLUMN RefCode nvarchar(50)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPOMLibrary' AND COLUMN_NAME='POM')
BEGIN
	ALTER TABLE pPOMLibrary ALTER COLUMN POM nvarchar(50)
END
GO


INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES              ('DB_Version', '5.0.0000', '03874', GetDate())
GO
