IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingStyle' AND COLUMN_NAME='SourcingHeaderID')
BEGIN
ALTER TABLE [pSourcingStyle]
ADD [SourcingHeaderID] uniqueidentifier NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingStyle' AND COLUMN_NAME='Styleset')
BEGIN
ALTER TABLE [pSourcingStyle]
ADD Styleset int NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingTradePartner' AND COLUMN_NAME='SourcingHeaderID')
BEGIN
ALTER TABLE [pSourcingTradePartner]
ADD [SourcingHeaderID] uniqueidentifier NULL
END


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingHeader' AND COLUMN_NAME='Custom1')
BEGIN
ALTER TABLE [pSourcingHeader]
ADD [Custom1] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingHeader' AND COLUMN_NAME='Custom2')
BEGIN
ALTER TABLE [pSourcingHeader]
ADD [Custom2] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingHeader' AND COLUMN_NAME='Custom3')
BEGIN
ALTER TABLE [pSourcingHeader]
ADD [Custom3] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingHeader' AND COLUMN_NAME='Custom4')
BEGIN
ALTER TABLE [pSourcingHeader]
ADD [Custom4] nvarchar(200) NULL
END


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingHeader' AND COLUMN_NAME='Custom5')
BEGIN
ALTER TABLE [pSourcingHeader]
ADD [Custom5] nvarchar(200) NULL
END


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingHeader' AND COLUMN_NAME='Custom6')
BEGIN
ALTER TABLE [pSourcingHeader]
ADD [Custom6] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingHeader' AND COLUMN_NAME='Custom7')
BEGIN
ALTER TABLE [pSourcingHeader]
ADD [Custom7] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingHeader' AND COLUMN_NAME='Custom8')
BEGIN
ALTER TABLE [pSourcingHeader]
ADD [Custom8] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingHeader' AND COLUMN_NAME='Custom9')
BEGIN
ALTER TABLE [pSourcingHeader]
ADD [Custom9] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingHeader' AND COLUMN_NAME='Custom10')
BEGIN
ALTER TABLE [pSourcingHeader]
ADD [Custom10] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingStyle' AND COLUMN_NAME='Custom1')
BEGIN
ALTER TABLE pSourcingStyle
ADD [Custom1] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingStyle' AND COLUMN_NAME='Custom2')
BEGIN
ALTER TABLE pSourcingStyle
ADD [Custom2] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingStyle' AND COLUMN_NAME='Custom3')
BEGIN
ALTER TABLE pSourcingStyle
ADD [Custom3] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingStyle' AND COLUMN_NAME='Custom4')
BEGIN
ALTER TABLE pSourcingStyle
ADD [Custom4] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingStyle' AND COLUMN_NAME='Custom5')
BEGIN
ALTER TABLE pSourcingStyle
ADD [Custom5] nvarchar(200) NULL
END


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingTradePartner' AND COLUMN_NAME='Custom1')
BEGIN
ALTER TABLE pSourcingTradePartner
ADD [Custom1] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingTradePartner' AND COLUMN_NAME='Custom2')
BEGIN
ALTER TABLE pSourcingTradePartner
ADD [Custom2] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingTradePartner' AND COLUMN_NAME='Custom3')
BEGIN
ALTER TABLE pSourcingTradePartner
ADD [Custom3] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingTradePartner' AND COLUMN_NAME='Custom4')
BEGIN
ALTER TABLE pSourcingTradePartner
ADD [Custom4] nvarchar(200) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingTradePartner' AND COLUMN_NAME='Custom5')
BEGIN
ALTER TABLE pSourcingTradePartner
ADD [Custom5] nvarchar(200) NULL
END


GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES     ('DB_Version', '5.0.0000', '04089', GetDate())
GO