IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pAMLMeasLbl' AND COLUMN_NAME = 'MeasLblDesc')
BEGIN
	ALTER TABLE pAMLMeasLbl ADD MeasLblDesc NVARCHAR(200) NULL
END
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES     ('DB_Version', '5.0.0000', '04353', GetDate())
GO
