IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pStyleQuoteItem' AND COLUMN_NAME = N'TechPack')
BEGIN 
	ALTER TABLE pStyleQuoteItem ADD TechPack UNIQUEIDENTIFIER NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pSourcingCommitmentItem' AND COLUMN_NAME = N'TechPack')
BEGIN 
	ALTER TABLE pSourcingCommitmentItem ADD TechPack UNIQUEIDENTIFIER NULL
END
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES   ('DB_Version', '5.0.0000', '04518', GetDate())
GO
