IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='pBatchQueueStyleMaterialTmp' AND COLUMN_NAME='StyleBOMDimensionID')
BEGIN
	ALTER TABLE pBatchQueueStyleMaterialTmp ADD StyleBOMDimensionID UNIQUEIDENTIFIER DEFAULT '00000000-0000-0000-0000-000000000000'
END

GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES     ('DB_Version', '5.0.0000', '04654', GetDate())
GO
