IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='pMaterial' AND COLUMN_NAME='DutyCategoryID')
BEGIN
	ALTER TABLE pMaterial ADD DutyCategoryID UNIQUEIDENTIFIER NULL
END


INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '5.0.0000', '04702', GetDate())
GO
