IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'sCurrencyType' AND COLUMN_NAME = 'CountryName')
BEGIN
	ALTER TABLE sCurrencyType ADD CountryName NVARCHAR(200)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'sExchangeRateItem' AND COLUMN_NAME = 'Rate')
BEGIN
	ALTER TABLE sExchangeRateItem ALTER COLUMN Rate DECIMAL(18,4)
END
GO


CREATE TABLE #tmpCurrency (
	RowNum INT IDENTITY,
	CountryName NVARCHAR(200),
	Currency NVARCHAR(50),
	Code NVARCHAR(5)
)

INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Afghanistan','Afghani','AFN')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Albania','Lek','ALL')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Algeria','Dinar','DZD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Angola','Kwanza','AOA')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Argentina','Peso','ARS')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Armenia','Dram','AMD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Aruba','Guilder','AWG')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Australia','Dollar','AUD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Azerbaijan','New Manat','AZN')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Bahamas','Dollar','BSD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Bahrain','Dinar','BHD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Bangladesh','Taka','BDT')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Barbados','Dollar','BBD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Belarus','Ruble','BYR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Belize','Dollar','BZD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Bermuda','Dollar','BMD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Bhutan','Ngultrum','BTN')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Bolivia','Boliviano','BOB')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Bosnia and Herzegovina','Marka (Conv.)','BAM')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Botswana','Pula','BWP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Brazil','Real','BRL')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Brunei Darussalam','Dollar','BND')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Bulgaria','Lev','BGN')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Burundi','Franc','BIF')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Cambodia','Riel','KHR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Canada','Dollar','CAD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Cape Verde','Escudo','CVE')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Cayman Islands','Dollar','KYD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Chile','Peso','CLP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('China','Yuan Renminbi','CNY')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Colombia','Peso','COP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Comoros','Franc','KMF')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Congo/Kinshasa','Franc','CDF')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Costa Rica','Colon','CRC')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Croatia','Kuna','HRK')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Cuba','Peso (Conv.)','CUC')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Cuba','Peso','CUP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Czech Republic','Koruna','CZK')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Denmark','Krone','DKK')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Djibouti','Franc','DJF')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Dominican Republic','Peso','DOP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('East Caribbean','Dollar','XCD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Egypt','Pound','EGP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('El Salvador','Colon','SVC')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Eritrea','Nakfa','ERN')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Ethiopia','Birr','ETB')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Euro Member Countries','Euro','EUR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Falkland Islands (Malvinas)','Pound','FKP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Fiji','Dollar','FJD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Gambia','Dalasi','GMD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Georgia','Lari','GEL')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Ghana','Cedi','GHS')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Gibraltar','Pound','GIP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Guatemala','Quetzal','GTQ')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Guernsey','Pound','GGP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Guinea','Franc','GNF')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Guyana','Dollar','GYD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Haiti','Gourde','HTG')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Honduras','Lempira','HNL')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Hong Kong','Dollar','HKD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Hungary','Forint','HUF')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Iceland','Krona','ISK')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('India','Rupee','INR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Indonesia','Rupiah','IDR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Iran','Rial','IRR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Iraq','Dinar','IQD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Isle of Man','Pound','IMP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Israel','Shekel','ILS')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Jamaica','Dollar','JMD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Japan','Yen','JPY')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Jersey','Pound','JEP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Jordan','Dinar','JOD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Kazakhstan','Tenge','KZT')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Kenya','Shilling','KES')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Korea (North)','Won','KPW')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Korea (South)','Won','KRW')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Kuwait','Dinar','KWD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Kyrgyzstan','Som','KGS')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Laos','Kip','LAK')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Latvia','Lat','LVL')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Lebanon','Pound','LBP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Lesotho','Loti','LSL')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Liberia','Dollar','LRD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Libya','Dinar','LYD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Lithuania','Litas','LTL')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Macau','Pataca','MOP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Macedonia','Denar','MKD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Madagascar','Ariary','MGA')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Malawi','Kwacha','MWK')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Malaysia','Ringgit','MYR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Maldives (Maldive Islands)','Rufiyaa','MVR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Mauritania','Ouguiya','MRO')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Mauritius','Rupee','MUR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Mexico','Peso','MXN')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Moldova','Leu','MDL')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Mongolia','Tughrik','MNT')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Morocco','Dirham','MAD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Mozambique','Metical','MZN')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Myanmar (Burma)','Kyat','MMK')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Namibia','Dollar','NAD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Nepal','Rupee','NPR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Netherlands Antilles','Guilder','ANG')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('New Zealand','Dollar','NZD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Nicaragua','Cordoba','NIO')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Nigeria','Naira','NGN')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Norway','Krone','NOK')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Oman','Rial','OMR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Pakistan','Rupee','PKR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Panama','Balboa','PAB')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Papua New Guinea','Kina','PGK')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Paraguay','Guarani','PYG')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Peru Nuevo','Sol','PEN')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Philippines','Peso','PHP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Poland','Zloty','PLN')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Qatar','Riyal','QAR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Romania','New Leu','RON')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Russia','Ruble','RUB')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Rwanda','Franc','RWF')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Saint Helena','Pound','SHP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Samoa','Tala','WST')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('São Tomé and Príncipe','Dobra','STD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Saudi Arabia','riyal','SAR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Seborga','Luigino','SPL*')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Serbia','Dinar','RSD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Seychelles','Rupee','SCR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Sierra Leone','Leone','SLL')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Singapore','Dollar','SGD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Solomon Islands','Dollar','SBD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Somalia','Shilling','SOS')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('South Africa','Rand','ZAR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Sri Lanka','Rupee','LKR')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Sudan','Pound','SDG')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Suriname','Dollar','SRD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Swaziland','Lilangeni','SZL')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Sweden','Krona','SEK')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Switzerland','Franc','CHF')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Syria','Pound','SYP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Taiwan New','Dollar','TWD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Tajikistan','Somoni','TJS')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Tanzania','Shilling','TZS')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Thailand','Baht','THB')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Tonga','Pa''anga','TOP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Trinidad and Tobago','Dollar','TTD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Tunisia','Dinar','TND')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Turkey','Lira','TRY')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Turkmenistan','Manat','TMT')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Tuvalu','Dollar','TVD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Uganda','Shilling','UGX')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Ukraine','Hryvna','UAH')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('United Arab Emirates','Dirham','AED')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('United Kingdom','Pound','GBP')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('United States','Dollar','USD')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Uruguay','Peso','UYU')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Uzbekistan','Som','UZS')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Vanuatu','Vatu','VUV')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Venezuela','Bolivar','VEF')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Viet Nam','Dong','VND')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Yemen','Rial','YER')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Zambia','Kwacha','ZMW')
INSERT INTO #tmpCurrency (CountryName, Currency, Code) VALUES ('Zimbabwe','Dollar','ZWD')

DECLARE @iRow INT
DECLARE @iCount INT
DECLARE @Country NVARCHAR(200)
DECLARE @Currency NVARCHAR(50)
DECLARE @Code NVARCHAR(5)

SET @iRow = 1
SELECT @iCount = COUNT(*) FROM #tmpCurrency

WHILE @iRow <= @iCount
BEGIN
	SELECT @Country = CountryName, @Currency = Currency, @Code = Code FROM #tmpCurrency WHERE RowNum = @iRow

	IF NOT EXISTS (SELECT * FROM sCurrencyType WHERE CustomKey = @Code)
	BEGIN
		INSERT INTO sCurrencyType (CustomKey, Custom, CountryName, Active)
		VALUES (@Code, @Currency, @Country, 1)
	END
	ELSE
	BEGIN
		UPDATE sCurrencyType SET Custom = @Currency, CountryName = @Country WHERE CustomKey = @Code
	END

	SET @iRow = @iRow + 1
END

DROP TABLE #tmpCurrency

GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '5.0.0000', '04710', GetDate())
GO
