/****** Object:  StoredProcedure [dbo].[spx_StyleRemoval_Log_INSERT]    Script Date: 02/05/2013 12:28:03 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[spx_StyleRemoval_Log_INSERT]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[spx_StyleRemoval_Log_INSERT]
GO

/****** Object:  StoredProcedure [dbo].[spx_StyleRemoval_Log_INSERT]    Script Date: 02/05/2013 12:28:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[spx_StyleRemoval_Log_INSERT]
	@StyleID UNIQUEIDENTIFIER,
	@TeamID UNIQUEIDENTIFIER,
	@RemovalReasonID UNIQUEIDENTIFIER,
	@RemovalComment NVARCHAR(500),
	@RemDate DATETIME
AS
BEGIN
	
	INSERT INTO [dbo].[pStyleRemoval]
           ([RemovalTeamID]
           ,[RemovalReasonID]
           ,[RemovalComment]
           ,[RemovalDate]
           ,[StyleID]
           ,[StyleType]
           ,[WorkflowType]
           ,[StyleNo]
           ,[Description]
           ,[StyleCategory]
           ,[SizeClass]
           ,[SizeRange]
           ,[DueDate]
           ,[RecDate]
           ,[DesignSketchID]
           ,[TechSketchID]
           ,[ConceptSketchID]
           ,[ColorSketchID]
           ,[DesignSketchVersion]
           ,[TechSketchVersion]
           ,[ConceptSketchVersion]
           ,[ColorSketchVersion]
           ,[DetailSketchID1]
           ,[DetailSketchID2]
           ,[DetailSketchID3]
           ,[DetailSketchID4]
           ,[DetailSketchVersion1]
           ,[DetailSketchVersion2]
           ,[DetailSketchVersion3]
           ,[DetailSketchVersion4]
           ,[SpecSketchID1]
           ,[SpecSketchID2]
           ,[SpecSketchID3]
           ,[SpecSketchID4]
           ,[SpecSketchVersion1]
           ,[SpecSketchVersion2]
           ,[SpecSketchVersion3]
           ,[SpecSketchVersion4]
           ,[Markup]
           ,[CustomField1]
           ,[CustomField2]
           ,[CustomField3]
           ,[CustomField4]
           ,[CustomField5]
           ,[CustomField6]
           ,[CustomField7]
           ,[CustomField8]
           ,[CustomField9]
           ,[CustomField10]
           ,[CustomField11]
           ,[CustomField12]
           ,[CustomField13]
           ,[CustomField14]
           ,[CustomField15]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[CustomField16]
           ,[CustomField17]
           ,[CustomField18]
           ,[CustomField19]
           ,[CustomField20]
           ,[CustomField21]
           ,[CustomField22]
           ,[CustomField23]
           ,[CustomField24]
           ,[CustomField25]
           ,[CustomField26]
           ,[CustomField27]
           ,[CustomField28]
           ,[CustomField29]
           ,[CustomField30]
           ,[CustomField31]
           ,[CustomField32]
           ,[CustomField33]
           ,[CustomField34]
           ,[CustomField35]
           ,[CustomField36]
           ,[CustomField37]
           ,[CustomField38]
           ,[CustomField39]
           ,[CustomField40]
           ,[IntroSeasonYearID]
           ,[DesignSketchBackID]
           ,[DesignSketchBackVersion]
           ,[OwnerGroup]
           ,[StartDate]
           ,[PlannedDueDate]
           ,[PlannedStartDate]
           ,[ScheduleBy]
           ,[EnforceDependency]
           ,[WorkflowTemplateID])
	SELECT
		@TeamID,
		@RemovalReasonID,
		@RemovalComment,
		@RemDate,
		@StyleID,
		[StyleType]
       ,[WorkflowType]
       ,[StyleNo]
       ,[Description]
       ,[StyleCategory]
       ,[SizeClass]
       ,[SizeRange]
       ,[DueDate]
       ,[RecDate]
       ,[DesignSketchID]
       ,[TechSketchID]
       ,[ConceptSketchID]
       ,[ColorSketchID]
       ,[DesignSketchVersion]
       ,[TechSketchVersion]
       ,[ConceptSketchVersion]
       ,[ColorSketchVersion]
       ,[DetailSketchID1]
       ,[DetailSketchID2]
       ,[DetailSketchID3]
       ,[DetailSketchID4]
       ,[DetailSketchVersion1]
       ,[DetailSketchVersion2]
       ,[DetailSketchVersion3]
       ,[DetailSketchVersion4]
       ,[SpecSketchID1]
       ,[SpecSketchID2]
       ,[SpecSketchID3]
       ,[SpecSketchID4]
       ,[SpecSketchVersion1]
       ,[SpecSketchVersion2]
       ,[SpecSketchVersion3]
       ,[SpecSketchVersion4]
       ,[Markup]
       ,[CustomField1]
       ,[CustomField2]
       ,[CustomField3]
       ,[CustomField4]
       ,[CustomField5]
       ,[CustomField6]
       ,[CustomField7]
       ,[CustomField8]
       ,[CustomField9]
       ,[CustomField10]
       ,[CustomField11]
       ,[CustomField12]
       ,[CustomField13]
       ,[CustomField14]
       ,[CustomField15]
       ,[CUser]
       ,[CDate]
       ,[MUser]
       ,[MDate]
       ,[CustomField16]
       ,[CustomField17]
       ,[CustomField18]
       ,[CustomField19]
       ,[CustomField20]
       ,[CustomField21]
       ,[CustomField22]
       ,[CustomField23]
       ,[CustomField24]
       ,[CustomField25]
       ,[CustomField26]
       ,[CustomField27]
       ,[CustomField28]
       ,[CustomField29]
       ,[CustomField30]
       ,[CustomField31]
       ,[CustomField32]
       ,[CustomField33]
       ,[CustomField34]
       ,[CustomField35]
       ,[CustomField36]
       ,[CustomField37]
       ,[CustomField38]
       ,[CustomField39]
       ,[CustomField40]
       ,[IntroSeasonYearID]
       ,[DesignSketchBackID]
       ,[DesignSketchBackVersion]
       ,[OwnerGroup]
       ,[StartDate]
       ,[PlannedDueDate]
       ,[PlannedStartDate]
       ,[ScheduleBy]
       ,[EnforceDependency]
       ,[WorkflowTemplateID]
	FROM pStyleHeader
	WHERE StyleID = @StyleID
           
END

GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '5.0.0000', '04973', GetDate())
GO
