IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
				WHERE TABLE_NAME='pStyleBOM'
				AND COLUMN_NAME='StyleMaterialCopyMasterID')
BEGIN
	ALTER TABLE pStyleBOM ADD StyleMaterialCopyMasterID UNIQUEIDENTIFIER NULL
END

GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
				WHERE TABLE_NAME='pStyleBOMDimension'
				AND COLUMN_NAME='StyleBOMDimensionCopyMasterID')
BEGIN
	ALTER TABLE pStyleBOMDimension ADD StyleBOMDimensionCopyMasterID UNIQUEIDENTIFIER NULL
END

GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
				WHERE TABLE_NAME='pStyleNBOLItems'
				AND COLUMN_NAME='StyleNBOLItemCopyMasterID')
BEGIN
	ALTER TABLE pStyleNBOLItems ADD StyleNBOLItemCopyMasterID UNIQUEIDENTIFIER NULL
END

GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
				WHERE TABLE_NAME='pStyleNBOLHeader'
				AND COLUMN_NAME='StyleNBOLHeaderCopyMasterID')
BEGIN
	ALTER TABLE pStyleNBOLHeader ADD StyleNBOLHeaderCopyMasterID UNIQUEIDENTIFIER NULL
END

GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '5.0.0000', '05096', GetDate())
GO
