IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[spx_Style_Marker_Copy]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[spx_Style_Marker_Copy]
GO


CREATE PROCEDURE [dbo].[spx_Style_Marker_Copy] (
@StyleID UNIQUEIDENTIFIER ,
@NewStyleID UNIQUEIDENTIFIER ,
@MUser nvarchar(200),
@MDate datetime
)
AS
BEGIN

INSERT INTO dbo.[pBodyMarker]
           ([ID]
           ,[BodyID]
           ,[StyleID]
           ,[StyleSet]
           ,[Marker_Code]
           ,[Marker_Name]
           ,[Location]
           ,[Last_Updated]
           ,[IsActive]
           ,[IsLinkedBF]
           ,[IsLinked]
           ,[Usage]
           ,[LossFactor]
           ,[LossFactor_pct]
           ,[TotalUsage]
           ,[AdjustedUsage]
           ,[Marker_Description]
           ,[Marker_CrOpId]
           ,[Marker_Create]
           ,[Marker_RevOp1]
           ,[CDate]
           ,[CUser]
           ,[MUser]
           ,[MDate]
           ,[Marker_Rev1]
           ,[Marker_RevOp2]
           ,[Marker_Rev2]
           ,[Marker_Width]
           ,[Marker_Length]
           ,[Marker_Total_Perim]
           ,[Marker_Total_Area]
           ,[Marker_Goal]
           ,[Marker_Efficiency]
           ,[Marker_Notches]
           ,[Marker_Drillholes]
           ,[Marker_Corners]
           ,[Marker_Message]
           ,[Marker_nModels]
           ,[Marker_nPieces]
           ,[Marker_PlacPieces]
           ,[Marker_nSizes]
           ,[Marker_nBundles]
           ,[Marker_Plac_Bndl]
           ,[Marker_Bias]
           ,[Marker_Flip]
           ,[Marker_Nap]
           ,[Marker_NCEdits]
           ,[Marker_Spread]
           ,[Marker_Closed]
           ,[Marker_DieBlk]
           ,[Marker_Tubular]
           ,[Marker_StripePlaid]
           ,[Marker_nStripes]
           ,[Marker_nPlaids]
           ,[Marker_5_Star]
           ,[Marker_Max_Splice]
           ,[Marker_nSplices]
           ,[Marker_XVariance]
           ,[Marker_YVariance]
           ,[Marker_Image_SN]
           ,[Marker_Image_Name]
           ,[Marker_Comments]
           ,[CADCatId]
           ,[Category]
           ,[SubCat]
           ,[SubCatType]
           ,[Class]
           ,[UserDefined1]
           ,[UserDefined2]
           ,[UserDefined3]
           ,[UserDefined4]
           ,[UserDefined5]
           ,[PreferMetric]
           ,[IsCosting]
           ,[IsApproved]
           ,[Sizes]
           ,[EfficiencyType]
           ,[LastCADRefresh]
           ,[PlotFileLocation]
           ,[NotchFile]
           ,[AnnotationFile]
           ,[StorageType]
           ,[mMarker_Width]
           ,[mMarker_Length]
           ,[mMarker_Total_Perim]
           ,[mMarker_Total_Area]
           ,[Yield_per_Bundle]
           ,[Yield_per_Dozen]
           ,[mYield_per_Bundle]
           ,[mYield_per_Dozen]
           ,[ImageID]
           ,[IsForAveraging]
           )  
SELECT	   NEWID()
           ,[BodyID]
           ,@NewStyleID as StyleID 
           ,StyleSet   
           ,[Marker_Code]
           ,[Marker_Name]
           ,[Location]
           ,[Last_Updated]
           ,[IsActive]
           ,[IsLinkedBF]
           ,[IsLinked]
           ,[Usage]
           ,[LossFactor]
           ,[LossFactor_pct]
           ,[TotalUsage]
           ,[AdjustedUsage]
           ,[Marker_Description]
           ,[Marker_CrOpId]
           ,[Marker_Create]
           ,[Marker_RevOp1]
           , @MDate as [CDate]
           , @MUser as [CUser]
           , @MUser as [MUser]
           , @MDate as [MDate]
           ,[Marker_Rev1]
           ,[Marker_RevOp2]
           ,[Marker_Rev2]
           ,[Marker_Width]
           ,[Marker_Length]
           ,[Marker_Total_Perim]
           ,[Marker_Total_Area]
           ,[Marker_Goal]
           ,[Marker_Efficiency]
           ,[Marker_Notches]
           ,[Marker_Drillholes]
           ,[Marker_Corners]
           ,[Marker_Message]
           ,[Marker_nModels]
           ,[Marker_nPieces]
           ,[Marker_PlacPieces]
           ,[Marker_nSizes]
           ,[Marker_nBundles]
           ,[Marker_Plac_Bndl]
           ,[Marker_Bias]
           ,[Marker_Flip]
           ,[Marker_Nap]
           ,[Marker_NCEdits]
           ,[Marker_Spread]
           ,[Marker_Closed]
           ,[Marker_DieBlk]
           ,[Marker_Tubular]
           ,[Marker_StripePlaid]
           ,[Marker_nStripes]
           ,[Marker_nPlaids]
           ,[Marker_5_Star]
           ,[Marker_Max_Splice]
           ,[Marker_nSplices]
           ,[Marker_XVariance]
           ,[Marker_YVariance]
           ,[Marker_Image_SN]
           ,[Marker_Image_Name]
           ,[Marker_Comments]
           ,[CADCatId]
           ,[Category]
           ,[SubCat]
           ,[SubCatType]
           ,[Class]
           ,[UserDefined1]
           ,[UserDefined2]
           ,[UserDefined3]
           ,[UserDefined4]
           ,[UserDefined5]
           ,[PreferMetric]
           ,[IsCosting]
           ,[IsApproved]
           ,[Sizes]
           ,[EfficiencyType]
           ,[LastCADRefresh]
           ,[PlotFileLocation]
           ,[NotchFile]
           ,[AnnotationFile]
           ,[StorageType]
           ,[mMarker_Width]
           ,[mMarker_Length]
           ,[mMarker_Total_Perim]
           ,[mMarker_Total_Area]
           ,[Yield_per_Bundle]
           ,[Yield_per_Dozen]
           ,[mYield_per_Bundle]
           ,[mYield_per_Dozen]
           ,[ImageID]
           ,[IsForAveraging]
FROM pBodyMarker WHERE StyleID = @StyleID

END
GO



INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '5.0.0000', '05100', GetDate())
GO
