IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='pLineFolder' AND COLUMN_NAME='LineFolderDivisionID')
BEGIN
	ALTER TABLE pLineFolder ADD LineFolderDivisionID UNIQUEIDENTIFIER
END

GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='pLineFolder' AND COLUMN_NAME='Active')
BEGIN
	ALTER TABLE pLineFolder ADD Active INT DEFAULT 1
END

GO

UPDATE pLineFolder SET Active = 1 WHERE Active IS NULL

GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '0.5.0000', '05317', GetDate())
GO
