IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'iCustom1' AND COLUMN_NAME = 'BrandID')
BEGIN
	ALTER TABLE iCustom1 ADD BrandID UNIQUEIDENTIFIER 
END
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '0.5.0000', '06205', GetDate())
GO
