IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pImage' AND COLUMN_NAME = 'TradePartnerID')
BEGIN
	ALTER TABLE pImage ADD TradePartnerID UNIQUEIDENTIFIER
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pImageType' AND COLUMN_NAME = 'srmOnAccess')
BEGIN
	ALTER TABLE pImageType ADD srmOnAccess INT
END
GO

UPDATE pImageType SET srmOnAccess = CASE WHEN ImageType = 'Trade Partner' THEN 1 ELSE 0 END
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES     ('DB_Version', '0.5.0000', '06684', GetDate())
GO
