IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleQuoteComment' AND COLUMN_NAME = 'CContactID')
BEGIN
	ALTER TABLE pStyleQuoteComment ADD CContactID UNIQUEIDENTIFIER
END
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '0.5.0000', '06803', GetDate())
GO