IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleCopyColorTmp' AND COLUMN_NAME = 'StyleColorwaySeasonYearID')
BEGIN
	ALTER TABLE pStyleCopyColorTmp ADD StyleColorwaySeasonYearID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleCopyColorTmp' AND COLUMN_NAME = 'ColorPaletteID')
BEGIN
	ALTER TABLE pStyleCopyColorTmp ADD ColorPaletteID UNIQUEIDENTIFIER
END

GO


INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '0.5.0000', '06812', GetDate())
GO
