IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pNBOLOperationType' AND COLUMN_NAME = 'CurrencyType')
BEGIN
	ALTER TABLE pNBOLOperationType ADD CurrencyType NVARCHAR(5)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pNBOLTemplateItem' AND COLUMN_NAME = 'CurrencyType')
BEGIN
	ALTER TABLE pNBOLTemplateItem ADD CurrencyType NVARCHAR(5)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleNBOLItems' AND COLUMN_NAME = 'CurrencyType')
BEGIN
	ALTER TABLE pStyleNBOLItems ADD CurrencyType NVARCHAR(5)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleNBOLHeader' AND COLUMN_NAME = 'ExchangeRateItemID')
BEGIN
	ALTER TABLE pStyleNBOLHeader ADD ExchangeRateItemID UNIQUEIDENTIFIER
END

GO


INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '0.5.0000', '06991', GetDate())
GO
