IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleCostingHeader' AND COLUMN_NAME = 'CurrencyType')
BEGIN
	ALTER TABLE pStyleCostingHeader ADD CurrencyType NVARCHAR(5)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleCosting' AND COLUMN_NAME = 'ExchangeRateItemID')
BEGIN
	ALTER TABLE pStyleCosting ADD ExchangeRateItemID UNIQUEIDENTIFIER
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleCostingScenarioItems' AND COLUMN_NAME = 'ExchangeRateItemID')
BEGIN
	ALTER TABLE pStyleCostingScenarioItems ADD ExchangeRateItemID UNIQUEIDENTIFIER
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleCosting' AND COLUMN_NAME = 'BOMCurrencyType')
BEGIN
	ALTER TABLE pStyleCosting ADD BOMCurrencyType NVARCHAR(5)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleCosting' AND COLUMN_NAME = 'BOLCurrencyType')
BEGIN
	ALTER TABLE pStyleCosting ADD BOLCurrencyType NVARCHAR(5)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleCostingScenarioItems' AND COLUMN_NAME = 'BOMCurrencyType')
BEGIN
	ALTER TABLE pStyleCostingScenarioItems ADD BOMCurrencyType NVARCHAR(5)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleCostingScenarioItems' AND COLUMN_NAME = 'BOLCurrencyType')
BEGIN
	ALTER TABLE pStyleCostingScenarioItems ADD BOLCurrencyType NVARCHAR(5)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleCostingBOM' AND COLUMN_NAME = 'CurrencyType')
BEGIN
	ALTER TABLE pStyleCostingBOM ADD CurrencyType NVARCHAR(5)
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleCostingBOL' AND COLUMN_NAME = 'CurrencyType')
BEGIN
	ALTER TABLE pStyleCostingBOL ADD CurrencyType NVARCHAR(5)
END

GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '0.5.0000', '07054', GetDate())
GO
