IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pMilestoneTemplateItem' AND COLUMN_NAME = 'DependencyID')
BEGIN
	ALTER TABLE pMilestoneTemplateItem ADD DependencyID UNIQUEIDENTIFIER 
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pMilestoneTemplateItem' AND COLUMN_NAME = 'AlertDays')
BEGIN
	ALTER TABLE pMilestoneTemplateItem ADD AlertDays INT
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pMilestoneTemplateItem' AND COLUMN_NAME = 'SystemTriggerID')
BEGIN
	ALTER TABLE pMilestoneTemplateItem ADD SystemTriggerID UNIQUEIDENTIFIER
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pMilestoneTemplateItem' AND COLUMN_NAME = 'ParentID')
BEGIN
	ALTER TABLE pMilestoneTemplateItem ADD ParentID UNIQUEIDENTIFIER
END
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '0.5.0000', '07164', GetDate())
GO
