--pPlanningColor
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningColor' and COLUMN_NAME = N'CustomField1')
BEGIN
	ALTER TABLE pPlanningColor DROP COLUMN CustomField1
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningColor' and COLUMN_NAME = N'CustomField2')
BEGIN
	ALTER TABLE pPlanningColor DROP COLUMN CustomField2
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningColor' and COLUMN_NAME = N'CustomField3')
BEGIN
	ALTER TABLE pPlanningColor DROP COLUMN CustomField3
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningColor' and COLUMN_NAME = N'CustomField4')
BEGIN
	ALTER TABLE pPlanningColor DROP COLUMN CustomField4
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningColor' and COLUMN_NAME = N'CustomField5')
BEGIN
	ALTER TABLE pPlanningColor DROP COLUMN CustomField5
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningColor' and COLUMN_NAME = N'CustomField6')
BEGIN
	ALTER TABLE pPlanningColor DROP COLUMN CustomField6
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningColor' and COLUMN_NAME = N'CustomField7')
BEGIN
	ALTER TABLE pPlanningColor DROP COLUMN CustomField7
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningColor' and COLUMN_NAME = N'CustomField8')
BEGIN
	ALTER TABLE pPlanningColor DROP COLUMN CustomField8
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningColor' and COLUMN_NAME = N'CustomField9')
BEGIN
	ALTER TABLE pPlanningColor DROP COLUMN CustomField9
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningColor' and COLUMN_NAME = N'CustomField10')
BEGIN
	ALTER TABLE pPlanningColor DROP COLUMN CustomField10
END
GO

--pPlanningMaterial
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningMaterial' and COLUMN_NAME = N'CustomField1')
BEGIN
	ALTER TABLE pPlanningMaterial DROP COLUMN CustomField1
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningMaterial' and COLUMN_NAME = N'CustomField2')
BEGIN
	ALTER TABLE pPlanningMaterial DROP COLUMN CustomField2
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningMaterial' and COLUMN_NAME = N'CustomField3')
BEGIN
	ALTER TABLE pPlanningMaterial DROP COLUMN CustomField3
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningMaterial' and COLUMN_NAME = N'CustomField4')
BEGIN
	ALTER TABLE pPlanningMaterial DROP COLUMN CustomField4
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningMaterial' and COLUMN_NAME = N'CustomField5')
BEGIN
	ALTER TABLE pPlanningMaterial DROP COLUMN CustomField5
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningMaterial' and COLUMN_NAME = N'CustomField6')
BEGIN
	ALTER TABLE pPlanningMaterial DROP COLUMN CustomField6
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningMaterial' and COLUMN_NAME = N'CustomField7')
BEGIN
	ALTER TABLE pPlanningMaterial DROP COLUMN CustomField7
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningMaterial' and COLUMN_NAME = N'CustomField8')
BEGIN
	ALTER TABLE pPlanningMaterial DROP COLUMN CustomField8
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningMaterial' and COLUMN_NAME = N'CustomField9')
BEGIN
	ALTER TABLE pPlanningMaterial DROP COLUMN CustomField9
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningMaterial' and COLUMN_NAME = N'CustomField10')
BEGIN
	ALTER TABLE pPlanningMaterial DROP COLUMN CustomField10
END
GO


--pPlanning
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanning' and COLUMN_NAME = N'CustomField1')
BEGIN
	ALTER TABLE pPlanning DROP COLUMN CustomField1
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanning' and COLUMN_NAME = N'CustomField2')
BEGIN
	ALTER TABLE pPlanning DROP COLUMN CustomField2
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanning' and COLUMN_NAME = N'CustomField3')
BEGIN
	ALTER TABLE pPlanning DROP COLUMN CustomField3
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanning' and COLUMN_NAME = N'CustomField4')
BEGIN
	ALTER TABLE pPlanning DROP COLUMN CustomField4
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanning' and COLUMN_NAME = N'CustomField5')
BEGIN
	ALTER TABLE pPlanning DROP COLUMN CustomField5
END
GO


--pPlanningItem
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningItem' and COLUMN_NAME = N'PlanningItemCustom1')
BEGIN
	ALTER TABLE pPlanningItem DROP COLUMN PlanningItemCustom1
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningItem' and COLUMN_NAME = N'PlanningItemCustom2')
BEGIN
	ALTER TABLE pPlanningItem DROP COLUMN PlanningItemCustom2
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningItem' and COLUMN_NAME = N'PlanningItemCustom3')
BEGIN
	ALTER TABLE pPlanningItem DROP COLUMN PlanningItemCustom3
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningItem' and COLUMN_NAME = N'PlanningItemCustom4')
BEGIN
	ALTER TABLE pPlanningItem DROP COLUMN PlanningItemCustom4
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningItem' and COLUMN_NAME = N'PlanningItemCustom5')
BEGIN
	ALTER TABLE pPlanningItem DROP COLUMN PlanningItemCustom5
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningItem' and COLUMN_NAME = N'PlanningItemCustom6')
BEGIN
	ALTER TABLE pPlanningItem DROP COLUMN PlanningItemCustom6
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningItem' and COLUMN_NAME = N'PlanningItemCustom7')
BEGIN
	ALTER TABLE pPlanningItem DROP COLUMN PlanningItemCustom7
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningItem' and COLUMN_NAME = N'PlanningItemCustom8')
BEGIN
	ALTER TABLE pPlanningItem DROP COLUMN PlanningItemCustom8
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'pPlanningItem' and COLUMN_NAME = N'PlanningItemCustom9')
BEGIN
	ALTER TABLE pPlanningItem DROP COLUMN PlanningItemCustom9
END
GO


INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '0.5.0000', '07375', GetDate())
GO
