IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleSKUItem' AND COLUMN_NAME = 'LineFolderSKUHeaderID')
BEGIN
	ALTER TABLE pStyleSKUItem ADD LineFolderSKUHeaderID UNIQUEIDENTIFIER	
END
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '0.5.0000', '07429', GetDate())
GO
