IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'iCustom5' AND COLUMN_NAME = 'Active')
BEGIN
	ALTER TABLE iCustom5 ALTER COLUMN Active INT
END
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '0.5.0000', '07540', GetDate())
GO
