IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleQuoteItem' AND COLUMN_NAME = 'StyleSKUItemID')
BEGIN
	ALTER TABLE pStyleQuoteItem ADD StyleSKUItemID UNIQUEIDENTIFIER
END
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '0.5.0000', '08198', GetDate())
GO
