IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pTACalHoliday' AND COLUMN_NAME = 'TACalHolidayCountry')
BEGIN
	ALTER TABLE pTACalHoliday ADD TACalHolidayCountry NVARCHAR(5)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pTACalHoliday' AND COLUMN_NAME = 'InternalHoliday')
BEGIN
	ALTER TABLE pTACalHoliday ADD InternalHoliday INT NOT NULL DEFAULT 1
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pTACalHoliday' AND COLUMN_NAME = 'CDate')
BEGIN
	ALTER TABLE pTACalHoliday ADD CDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pTACalHoliday' AND COLUMN_NAME = 'CUser')
BEGIN
	ALTER TABLE pTACalHoliday ADD CUser NVARCHAR(200) NOT NULL DEFAULT 'System'
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pTACalHoliday' AND COLUMN_NAME = 'MDate')
BEGIN
	ALTER TABLE pTACalHoliday ADD MDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pTACalHoliday' AND COLUMN_NAME = 'MUser')
BEGIN
	ALTER TABLE pTACalHoliday ADD MUser NVARCHAR(200) NOT NULL DEFAULT 'System'
END
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '0.5.0000', '08475', GetDate())
GO
