IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleWorkflow' AND COLUMN_NAME = 'ActualStart')
	ALTER TABLE pStyleWorkflow ADD ActualStart DATETIME NULL
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleWorkflow' AND COLUMN_NAME = 'ActualEnd')
	ALTER TABLE pStyleWorkflow ADD ActualEnd DATETIME NULL
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '0.5.0000', '08473', GetDate())
GO
