IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleQuoteItem' AND COLUMN_NAME = 'WorkAssignedTo')
BEGIN
	ALTER TABLE pStyleQuoteItem ADD WorkAssignedTo INT
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleQuoteItem' AND COLUMN_NAME = 'ActualStart')
BEGIN
	ALTER TABLE pStyleQuoteItem ADD ActualStart DATETIME
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleQuoteItem' AND COLUMN_NAME = 'ActualEnd')
BEGIN
	ALTER TABLE pStyleQuoteItem ADD ActualEnd DATETIME
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleQuoteItem' AND COLUMN_NAME = 'WorkStart')
BEGIN
	ALTER TABLE pStyleQuoteItem ADD WorkStart DATETIME
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pStyleQuoteItem' AND COLUMN_NAME = 'WorkDue')
BEGIN
	ALTER TABLE pStyleQuoteItem ADD WorkDue DATETIME
END
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '0.5.0000', '08596', GetDate())
GO
