ALTER TABLE pSizeRange ALTER COLUMN SizeRangeCode NVARCHAR(400) NOT NULL;

ALTER TABLE pSizeRange ALTER COLUMN Size0 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size1 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size2 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size3 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size4 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size5 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size6 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size7 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size8 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size9 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size10 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size11 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size12 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size13 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size14 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size15 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size16 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size17 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size18 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size19 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size20 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size21 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size22 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size23 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size24 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size25 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size26 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size27 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size28 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size29 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size30 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size31 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size32 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size33 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size34 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size35 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size36 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size37 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size38 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size39 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size40 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size41 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size42 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size43 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size44 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size45 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size46 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size47 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size48 NVARCHAR(200);
ALTER TABLE pSizeRange ALTER COLUMN Size49 NVARCHAR(200);
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '6.1.0000', '09401', GetDate())
GO
