ALTER TABLE pPOMTemplate ALTER COLUMN Size0 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size1 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size2 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size3 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size4 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size5 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size6 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size7 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size8 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size9 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size10 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size11 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size12 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size13 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size14 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size15 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size16 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size17 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size18 NVARCHAR(200);
ALTER TABLE pPOMTemplate ALTER COLUMN Size19 NVARCHAR(200);
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '6.1.0000', '09509', GetDate())
GO

