IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dvtComponentSizeHeaderName' AND COLUMN_NAME='ItemKey')
BEGIN
	ALTER TABLE dvtComponentSizeHeaderName
	ALTER COLUMN ItemKey NVARCHAR(200) NOT NULL
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dvtComponentSizeHeaderName' AND COLUMN_NAME='ItemValue')
BEGIN
	ALTER TABLE dvtComponentSizeHeaderName
	ALTER COLUMN ItemValue NVARCHAR(400) NOT NULL
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dvtComponentTypeCode' AND COLUMN_NAME='ItemKey')
BEGIN
	ALTER TABLE dvtComponentTypeCode
	ALTER COLUMN ItemKey NVARCHAR(200) NOT NULL
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dvtComponentTypeCode' AND COLUMN_NAME='ItemValue')
BEGIN
	ALTER TABLE dvtComponentTypeCode
	ALTER COLUMN ItemValue NVARCHAR(400) NOT NULL
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dvtImageClass' AND COLUMN_NAME='ItemKey')
BEGIN
	ALTER TABLE dvtImageClass
	ALTER COLUMN ItemKey NVARCHAR(200) NOT NULL
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dvtImageClass' AND COLUMN_NAME='ItemValue')
BEGIN
	ALTER TABLE dvtImageClass
	ALTER COLUMN ItemValue NVARCHAR(400) NOT NULL
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='pTechPackCoverpage' AND COLUMN_NAME='Custom')
BEGIN
	ALTER TABLE pTechPackCoverpage
	ALTER COLUMN Custom NVARCHAR(400)
END
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '6.1.0000', '09872', GetDate())
GO
