DECLARE @AlterStmt NVARCHAR(MAX)

SELECT @AlterStmt = ISNULL(@AlterStmt + '; ', '') + 'ALTER TABLE ' + INFORMATION_SCHEMA.COLUMNS.TABLE_NAME + ' ALTER COLUMN ' + INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME + ' NVARCHAR(200)'
FROM INFORMATION_SCHEMA.COLUMNS
INNER JOIN INFORMATION_SCHEMA.TABLES ON INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = INFORMATION_SCHEMA.TABLES.TABLE_NAME
WHERE INFORMATION_SCHEMA.TABLES.TABLE_TYPE = 'BASE TABLE'
	AND COLUMN_NAME LIKE 'ItemDim_Name'
	AND DATA_TYPE = 'NVARCHAR'
	AND CHARACTER_MAXIMUM_LENGTH < 201

EXEC(@AlterStmt)
GO

INSERT INTO sVersion(AppName, Version, LastScriptRun, TimeStamp)
VALUES ('DB_Version', '6.1.0000', '10284', GetUTCDate())
GO
