--
--
-- A) This script assume you are in management studio in the database where you want data to be populated.
-- B) Change the plmOn30 to whatever database you want to pull data FROM. This is where you are going to
--    get the data for these empty tables
--
-- C) Each of these tables in this script are EMPTY after upgrading from 2.7 to 3.0. If you want or need
--    data in some of these tables and you know which ones feel free to delete tables that you DO NOT
--    want to pull from.
--
-- D) There are NO WHERE clauses on these insert statement so it will pull ALL data from the specified tables
--
--
--

SET IDENTITY_INSERT dbo.pBodyChange ON
GO

INSERT INTO pBodyChange([BodyChangeID],[BodyChangeNo],[BodyStatus],[WorkflowID],[BodyID],[BodySet],
                        [BodyChangeNotifyTo],[BodyChangeType],[BodyChangeDescription],
                        [BodyChangeBy],[BodyChangeDate],[ActiveID],[Active])
SELECT [BodyChangeID],[BodyChangeNo],[BodyStatus],[WorkflowID],[BodyID],[BodySet],
                        [BodyChangeNotifyTo],[BodyChangeType],[BodyChangeDescription],
                        [BodyChangeBy],[BodyChangeDate],[ActiveID],[Active]
from plmOn30.dbo.pBodyChange
GO

SET IDENTITY_INSERT dbo.pBodyChange OFF
GO

SET IDENTITY_INSERT dbo.pBodyHistory ON
GO

INSERT INTO pBodyHistory([BodyHistoryID],[BodyID],[TeamID],[CDate])
SELECT [BodyHistoryID],[BodyID],[TeamID],[CDate]
FROM plmOn30.dbo.pBodyHistory
go

SET IDENTITY_INSERT dbo.pBodyHistory OFF
GO

INSERT INTO pColorGroup
           ([ColorGroupID]
           ,[ColorGroupName]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[Sort]
           ,[CustomField1]
           ,[CustomField2]
           ,[Active])
SELECT [ColorGroupID]
           ,[ColorGroupName]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[Sort]
           ,[CustomField1]
           ,[CustomField2]
           ,[Active]
FROM plmOn30.dbo.pColorGroup
go

INSERT INTO pImageMultiPage
           ([ImageMultiPageID]
           ,[ImageID]
           ,[ImageNo]
           ,[ImageMultiPage1]
           ,[ImageMultiPage2]
           ,[ImageMultiPage3]
           ,[ImageMultiPage4]
           ,[ImageMultiPage5]
           ,[ImageMultiPage6]
           ,[ImageMultiPage7]
           ,[ImageMultiPage8]
           ,[ImageMultiPage9]
           ,[ImageMultiPage10]
           ,[ImageMultiPage11]
           ,[ImageMultiPage12]
           ,[ImageMultiPage13]
           ,[ImageMultiPage14]
           ,[ImageMultiPage15]
           ,[ImageMultiPage16]
           ,[ImageMultiPage17]
           ,[ImageMultiPage18]
           ,[ImageMultiPage19]
           ,[ImageMultiPage20]
           ,[ImageMultiPage21]
           ,[ImageMultiPage22]
           ,[ImageMultiPage23]
           ,[ImageMultiPage24]
           ,[ImageMultiPage25]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate])
SELECT [ImageMultiPageID]
           ,[ImageID]
           ,[ImageNo]
           ,[ImageMultiPage1]
           ,[ImageMultiPage2]
           ,[ImageMultiPage3]
           ,[ImageMultiPage4]
           ,[ImageMultiPage5]
           ,[ImageMultiPage6]
           ,[ImageMultiPage7]
           ,[ImageMultiPage8]
           ,[ImageMultiPage9]
           ,[ImageMultiPage10]
           ,[ImageMultiPage11]
           ,[ImageMultiPage12]
           ,[ImageMultiPage13]
           ,[ImageMultiPage14]
           ,[ImageMultiPage15]
           ,[ImageMultiPage16]
           ,[ImageMultiPage17]
           ,[ImageMultiPage18]
           ,[ImageMultiPage19]
           ,[ImageMultiPage20]
           ,[ImageMultiPage21]
           ,[ImageMultiPage22]
           ,[ImageMultiPage23]
           ,[ImageMultiPage24]
           ,[ImageMultiPage25]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
FROM plmOn30.dbo.pImageMultiPage
go


INSERT INTO pLineFolderType
           ([LineFolderTypeID]
           ,[LineFolderTypeName]
           ,[LineFolderTypeDescription]
           ,[LineFolderNewSchema]
           ,[LineFolderSchema]
           ,[LineFolderSchemaItem]
           ,[LineFolderSchemaSearch]
           ,[LineFolderItemSchemaSearch]
           ,[LineFolderItemSchema]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate])
SELECT [LineFolderTypeID]
           ,[LineFolderTypeName]
           ,[LineFolderTypeDescription]
           ,[LineFolderNewSchema]
           ,[LineFolderSchema]
           ,[LineFolderSchemaItem]
           ,[LineFolderSchemaSearch]
           ,[LineFolderItemSchemaSearch]
           ,[LineFolderItemSchema]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
FROM plmOn30.dbo.pLineFolderType
go

INSERT INTO pLinePlanAttributeType
           ([LinePlanAttributeTypeID]
           ,[LinePlanAttributeType]
           ,[SearchSchema]
           ,[DefaultSchema])
SELECT [LinePlanAttributeTypeID]
           ,[LinePlanAttributeType]
           ,[SearchSchema]
           ,[DefaultSchema]
FROM plmOn30.dbo.pLinePlanAttributeType
go


INSERT INTO pLinePlanColorItemTemp
           ([LinePlanColorItemTempID]
           ,[LinePlanColorItemID]
           ,[LinePlanColorGroupID]
           ,[LinePlanColorID]
           ,[LinePlanRangeID]
           ,[LinePlanID]
           ,[ColorPaletteID]
           ,[ColorFolderID]
           ,[ColorID]
           ,[ColorCode]
           ,[ColorName]
           ,[ColorImage]
           ,[ColorImageType]
           ,[ColorSource]
           ,[ColorNotes]
           ,[Hex]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[Change]
           ,[Active]
           ,[Sort])
 SELECT [LinePlanColorItemTempID]
           ,[LinePlanColorItemID]
           ,[LinePlanColorGroupID]
           ,[LinePlanColorID]
           ,[LinePlanRangeID]
           ,[LinePlanID]
           ,[ColorPaletteID]
           ,[ColorFolderID]
           ,[ColorID]
           ,[ColorCode]
           ,[ColorName]
           ,[ColorImage]
           ,[ColorImageType]
           ,[ColorSource]
           ,[ColorNotes]
           ,[Hex]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[Change]
           ,[Active]
           ,[Sort]
FROM plmOn30.dbo.pLinePlanColorItemTemp
go

INSERT INTO pLinePlanAttributeType
           ([LinePlanAttributeTypeID]
           ,[LinePlanAttributeType]
           ,[SearchSchema]
           ,[DefaultSchema])
SELECT [LinePlanAttributeTypeID]
           ,[LinePlanAttributeType]
           ,[SearchSchema]
           ,[DefaultSchema]
FROM plmOn30.dbo.pLinePlanAttributeType
go

INSERT INTO pLinePlanItemTemp
           ([LinePlanItemID]
           ,[LinePlanRangeID]
           ,[StyleID]
           ,[LinePlanStyleAttributeItemID]
           ,[LinePlanRangeTypeID]
           ,[MUser]
           ,[MDate])
SELECT [LinePlanItemID]
           ,[LinePlanRangeID]
           ,[StyleID]
           ,[LinePlanStyleAttributeItemID]
           ,[LinePlanRangeTypeID]
           ,[MUser]
           ,[MDate]
FROM plmOn30.dbo.pLinePlanItemTemp
go

INSERT INTO pLinePlanMaterialItemTemp
           ([LinePlanMaterialItemTempID]
           ,[LinePlanMaterialItemID]
           ,[LinePlanColorGroupID]
           ,[LinePlanID]
           ,[LinePlanRangeID]
           ,[MaterialID]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate])
SELECT [LinePlanMaterialItemTempID]
           ,[LinePlanMaterialItemID]
           ,[LinePlanColorGroupID]
           ,[LinePlanID]
           ,[LinePlanRangeID]
           ,[MaterialID]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
FROM plmOn30.dbo.pLinePlanMaterialItemTemp
go


INSERT INTO pLinePlanMultiClothColorTemp
           ([LinePlanColorItemTempID]
           ,[LinePlanColorGroupID]
           ,[LinePlanColorItemID]
           ,[MaterialGroupColorID]
           ,[MaterialColorID]
           ,[MaterialID]
           ,[StyleColorID]
           ,[StyleID]
           ,[StyleSet]
           ,[StyleColorStandardID]
           ,[StyleColorNo]
           ,[StyleColorName]
           ,[MainColor]
           ,[Sort]
           ,[Version]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser]
           ,[CopyStyleColorID]
           ,[ColorPaletteID]
           ,[SAPCode]
           ,[StyleColorDelivery1]
           ,[StyleColorDelivery2]
           ,[StyleColorDelivery3]
           ,[StyleColorDelivery4]
           ,[PLMCode]
           ,[StyleColorStatus]
           ,[CustomField1]
           ,[Units]
           ,[Yunique]
           ,[ColorType])
SELECT [LinePlanColorItemTempID]
           ,[LinePlanColorGroupID]
           ,[LinePlanColorItemID]
           ,[MaterialGroupColorID]
           ,[MaterialColorID]
           ,[MaterialID]
           ,[StyleColorID]
           ,[StyleID]
           ,[StyleSet]
           ,[StyleColorStandardID]
           ,[StyleColorNo]
           ,[StyleColorName]
           ,[MainColor]
           ,[Sort]
           ,[Version]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser]
           ,[CopyStyleColorID]
           ,[ColorPaletteID]
           ,[SAPCode]
           ,[StyleColorDelivery1]
           ,[StyleColorDelivery2]
           ,[StyleColorDelivery3]
           ,[StyleColorDelivery4]
           ,[PLMCode]
           ,[StyleColorStatus]
           ,[CustomField1]
           ,[Units]
           ,[Yunique]
           ,[ColorType]
FROM plmOn30.dbo.pLinePlanMultiClothColorTemp
go


INSERT INTO pLinePlanMultiClothStyleTemp
           ([LinePlanStyleTempID]
           ,[LinePlanColorGroupID]
           ,[MaterialGroupID]
           ,[StyleID]
           ,[StyleMasterID]
           ,[StyleWorkflowID]
           ,[StyleType]
           ,[WorkflowType]
           ,[StyleNo]
           ,[TempID]
           ,[TempNo]
           ,[CustomerNo]
           ,[DevelopmentID]
           ,[DevelopmentNo]
           ,[ConceptID]
           ,[ConceptNo]
           ,[SpecNo]
           ,[Description]
           ,[StyleCategory]
           ,[SizeClass]
           ,[SizeRange]
           ,[StyleSet]
           ,[TechPackId]
           ,[TechPackDate]
           ,[DueDate]
           ,[RecDate]
           ,[Customer]
           ,[Buyer]
           ,[Designer]
           ,[SampleMaker]
           ,[PatternMaker]
           ,[ProductionManager]
           ,[TechnicalDesigner]
           ,[StyleStatus]
           ,[StyleLocation]
           ,[WashType]
           ,[Pitch]
           ,[MaterialID]
           ,[MaterialImageID]
           ,[MaterialImageVersion]
           ,[MaterialNo]
           ,[MaterialName]
           ,[POMTempGroupID1]
           ,[POMTempGroupID2]
           ,[POMTempGroupID3]
           ,[POMTempGroupID4]
           ,[POMTempID1]
           ,[POMTempVersion1]
           ,[POMTempSizeClass1]
           ,[POMTempID2]
           ,[POMTempVersion2]
           ,[POMTempSizeClass2]
           ,[POMTempID3]
           ,[POMTempVersion3]
           ,[POMTempSizeClass3]
           ,[POMTempID4]
           ,[POMTempVersion4]
           ,[POMTempSizeClass4]
           ,[StyleMaterialID]
           ,[DesignSketchID]
           ,[TechSketchID]
           ,[ConceptSketchID]
           ,[ColorSketchID]
           ,[DesignSketchVersion]
           ,[TechSketchVersion]
           ,[ConceptSketchVersion]
           ,[ColorSketchVersion]
           ,[DetailSketchID1]
           ,[DetailSketchID2]
           ,[DetailSketchID3]
           ,[DetailSketchID4]
           ,[DetailSketchVersion1]
           ,[DetailSketchVersion2]
           ,[DetailSketchVersion3]
           ,[DetailSketchVersion4]
           ,[SpecSketchID1]
           ,[SpecSketchID2]
           ,[SpecSketchID3]
           ,[SpecSketchID4]
           ,[SpecSketchVersion1]
           ,[SpecSketchVersion2]
           ,[SpecSketchVersion3]
           ,[SpecSketchVersion4]
           ,[Markup]
           ,[TargetPrice]
           ,[SellingPrice]
           ,[CustomField1]
           ,[CustomField2]
           ,[CustomField3]
           ,[CustomField4]
           ,[CustomField5]
           ,[CustomField6]
           ,[CustomField7]
           ,[CustomField8]
           ,[CustomField9]
           ,[CustomField10]
           ,[CustomField11]
           ,[CustomField12]
           ,[CustomField13]
           ,[CustomField14]
           ,[CustomField15]
           ,[Pc1]
           ,[Pc2]
           ,[Pc3]
           ,[Pc4]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[Active]
           ,[Change]
           ,[Action]
           ,[NoColorCombo]
           ,[StyleVersion]
           ,[StyleDetail]
           ,[StyleDetail1]
           ,[StyleDetail2]
           ,[StyleAttribute]
           ,[LinePlanID]
           ,[LinePlanNo]
           ,[LinePlanSketchID]
           ,[LinePlanSketchVersion]
           ,[CustomField16]
           ,[CustomField17]
           ,[CustomField18]
           ,[CustomField19]
           ,[CustomField20]
           ,[CustomField21]
           ,[CustomField22]
           ,[CustomField23]
           ,[CustomField24]
           ,[CustomField25]
           ,[CustomField26]
           ,[CustomField27]
           ,[CustomField28]
           ,[CustomField29]
           ,[CustomField30]
           ,[PackagingNo]
           ,[StyleCopyID]
           ,[LinePlanItemID]
           ,[StyleStatusID]
           ,[BodyID]
           ,[TradePartnerID]
           ,[TradePartnerVendorID]
           ,[ProdDev]
           ,[HeaderLocked]
           ,[ReportingGroup])
SELECT [LinePlanStyleTempID]
           ,[LinePlanColorGroupID]
           ,[MaterialGroupID]
           ,[StyleID]
           ,[StyleMasterID]
           ,[StyleWorkflowID]
           ,[StyleType]
           ,[WorkflowType]
           ,[StyleNo]
           ,[TempID]
           ,[TempNo]
           ,[CustomerNo]
           ,[DevelopmentID]
           ,[DevelopmentNo]
           ,[ConceptID]
           ,[ConceptNo]
           ,[SpecNo]
           ,[Description]
           ,[StyleCategory]
           ,[SizeClass]
           ,[SizeRange]
           ,[StyleSet]
           ,[TechPackId]
           ,[TechPackDate]
           ,[DueDate]
           ,[RecDate]
           ,[Customer]
           ,[Buyer]
           ,[Designer]
           ,[SampleMaker]
           ,[PatternMaker]
           ,[ProductionManager]
           ,[TechnicalDesigner]
           ,[StyleStatus]
           ,[StyleLocation]
           ,[WashType]
           ,[Pitch]
           ,[MaterialID]
           ,[MaterialImageID]
           ,[MaterialImageVersion]
           ,[MaterialNo]
           ,[MaterialName]
           ,[POMTempGroupID1]
           ,[POMTempGroupID2]
           ,[POMTempGroupID3]
           ,[POMTempGroupID4]
           ,[POMTempID1]
           ,[POMTempVersion1]
           ,[POMTempSizeClass1]
           ,[POMTempID2]
           ,[POMTempVersion2]
           ,[POMTempSizeClass2]
           ,[POMTempID3]
           ,[POMTempVersion3]
           ,[POMTempSizeClass3]
           ,[POMTempID4]
           ,[POMTempVersion4]
           ,[POMTempSizeClass4]
           ,[StyleMaterialID]
           ,[DesignSketchID]
           ,[TechSketchID]
           ,[ConceptSketchID]
           ,[ColorSketchID]
           ,[DesignSketchVersion]
           ,[TechSketchVersion]
           ,[ConceptSketchVersion]
           ,[ColorSketchVersion]
           ,[DetailSketchID1]
           ,[DetailSketchID2]
           ,[DetailSketchID3]
           ,[DetailSketchID4]
           ,[DetailSketchVersion1]
           ,[DetailSketchVersion2]
           ,[DetailSketchVersion3]
           ,[DetailSketchVersion4]
           ,[SpecSketchID1]
           ,[SpecSketchID2]
           ,[SpecSketchID3]
           ,[SpecSketchID4]
           ,[SpecSketchVersion1]
           ,[SpecSketchVersion2]
           ,[SpecSketchVersion3]
           ,[SpecSketchVersion4]
           ,[Markup]
           ,[TargetPrice]
           ,[SellingPrice]
           ,[CustomField1]
           ,[CustomField2]
           ,[CustomField3]
           ,[CustomField4]
           ,[CustomField5]
           ,[CustomField6]
           ,[CustomField7]
           ,[CustomField8]
           ,[CustomField9]
           ,[CustomField10]
           ,[CustomField11]
           ,[CustomField12]
           ,[CustomField13]
           ,[CustomField14]
           ,[CustomField15]
           ,[Pc1]
           ,[Pc2]
           ,[Pc3]
           ,[Pc4]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[Active]
           ,[Change]
           ,[Action]
           ,[NoColorCombo]
           ,[StyleVersion]
           ,[StyleDetail]
           ,[StyleDetail1]
           ,[StyleDetail2]
           ,[StyleAttribute]
           ,[LinePlanID]
           ,[LinePlanNo]
           ,[LinePlanSketchID]
           ,[LinePlanSketchVersion]
           ,[CustomField16]
           ,[CustomField17]
           ,[CustomField18]
           ,[CustomField19]
           ,[CustomField20]
           ,[CustomField21]
           ,[CustomField22]
           ,[CustomField23]
           ,[CustomField24]
           ,[CustomField25]
           ,[CustomField26]
           ,[CustomField27]
           ,[CustomField28]
           ,[CustomField29]
           ,[CustomField30]
           ,[PackagingNo]
           ,[StyleCopyID]
           ,[LinePlanItemID]
           ,[StyleStatusID]
           ,[BodyID]
           ,[TradePartnerID]
           ,[TradePartnerVendorID]
           ,[ProdDev]
           ,[HeaderLocked]
           ,[ReportingGroup]
FROM plmOn30.dbo.pLinePlanMultiClothStyleTemp
go


INSERT INTO pLinePlanRangeAttribute
           ([LinePlanRangeAttributeID]
           ,[LinePlanStyleAttributeItemID]
           ,[AttributeID]
           ,[AttributeName]
           ,[LinePlanAttributeItemID1]
           ,[LinePlanAttributeItemID2]
           ,[LinePlanAttributeItemID3]
           ,[LinePlanAttributeItemID4]
           ,[LinePlanID]
           ,[LinePlanFinancialID]
           ,[LinePlanRange]
           ,[LinePlanRangeDelCO1]
           ,[LinePlanRangeDelNV1]
           ,[LinePlanRangeDelN1]
           ,[LinePlanRangeDelTL1]
           ,[LinePlanRangeDelCO2]
           ,[LinePlanRangeDelNV2]
           ,[LinePlanRangeDelN2]
           ,[LinePlanRangeDelTL2]
           ,[LinePlanRangeDelCO3]
           ,[LinePlanRangeDelNV3]
           ,[LinePlanRangeDelN3]
           ,[LinePlanRangeDelTL3]
           ,[LinePlanRangeDelCO4]
           ,[LinePlanRangeDelNV4]
           ,[LinePlanRangeDelN4]
           ,[LinePlanRangeDelTL4]
           ,[LinePlanRangeDelAVCO]
           ,[LinePlanRangeDelAVNV]
           ,[LinePlanRangeDelAVN]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[LinePlanFinancialSort])
SELECT [LinePlanRangeAttributeID]
           ,[LinePlanStyleAttributeItemID]
           ,[AttributeID]
           ,[AttributeName]
           ,[LinePlanAttributeItemID1]
           ,[LinePlanAttributeItemID2]
           ,[LinePlanAttributeItemID3]
           ,[LinePlanAttributeItemID4]
           ,[LinePlanID]
           ,[LinePlanFinancialID]
           ,[LinePlanRange]
           ,[LinePlanRangeDelCO1]
           ,[LinePlanRangeDelNV1]
           ,[LinePlanRangeDelN1]
           ,[LinePlanRangeDelTL1]
           ,[LinePlanRangeDelCO2]
           ,[LinePlanRangeDelNV2]
           ,[LinePlanRangeDelN2]
           ,[LinePlanRangeDelTL2]
           ,[LinePlanRangeDelCO3]
           ,[LinePlanRangeDelNV3]
           ,[LinePlanRangeDelN3]
           ,[LinePlanRangeDelTL3]
           ,[LinePlanRangeDelCO4]
           ,[LinePlanRangeDelNV4]
           ,[LinePlanRangeDelN4]
           ,[LinePlanRangeDelTL4]
           ,[LinePlanRangeDelAVCO]
           ,[LinePlanRangeDelAVNV]
           ,[LinePlanRangeDelAVN]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[LinePlanFinancialSort]
FROM plmOn30.dbo.pLinePlanRangeAttribute
go

INSERT INTO pLinePlanRangeAttributeTemp
           ([LinePlanRangeAttributeID]
           ,[LinePlanStyleAttributeItemID]
           ,[AttributeID]
           ,[AttributeName]
           ,[LinePlanAttributeItemID1]
           ,[LinePlanAttributeItemID2]
           ,[LinePlanAttributeItemID3]
           ,[LinePlanAttributeItemID4]
           ,[LinePlanID]
           ,[LinePlanFinancialID]
           ,[LinePlanRange]
           ,[LinePlanRangeDelCO1]
           ,[LinePlanRangeDelNV1]
           ,[LinePlanRangeDelN1]
           ,[LinePlanRangeDelTL1]
           ,[LinePlanRangeDelCO2]
           ,[LinePlanRangeDelNV2]
           ,[LinePlanRangeDelN2]
           ,[LinePlanRangeDelTL2]
           ,[LinePlanRangeDelCO3]
           ,[LinePlanRangeDelNV3]
           ,[LinePlanRangeDelN3]
           ,[LinePlanRangeDelTL3]
           ,[LinePlanRangeDelCO4]
           ,[LinePlanRangeDelNV4]
           ,[LinePlanRangeDelN4]
           ,[LinePlanRangeDelTL4]
           ,[LinePlanRangeDelAVCO]
           ,[LinePlanRangeDelAVNV]
           ,[LinePlanRangeDelAVN]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[LinePlanFinancialSort])
SELECT [LinePlanRangeAttributeID]
           ,[LinePlanStyleAttributeItemID]
           ,[AttributeID]
           ,[AttributeName]
           ,[LinePlanAttributeItemID1]
           ,[LinePlanAttributeItemID2]
           ,[LinePlanAttributeItemID3]
           ,[LinePlanAttributeItemID4]
           ,[LinePlanID]
           ,[LinePlanFinancialID]
           ,[LinePlanRange]
           ,[LinePlanRangeDelCO1]
           ,[LinePlanRangeDelNV1]
           ,[LinePlanRangeDelN1]
           ,[LinePlanRangeDelTL1]
           ,[LinePlanRangeDelCO2]
           ,[LinePlanRangeDelNV2]
           ,[LinePlanRangeDelN2]
           ,[LinePlanRangeDelTL2]
           ,[LinePlanRangeDelCO3]
           ,[LinePlanRangeDelNV3]
           ,[LinePlanRangeDelN3]
           ,[LinePlanRangeDelTL3]
           ,[LinePlanRangeDelCO4]
           ,[LinePlanRangeDelNV4]
           ,[LinePlanRangeDelN4]
           ,[LinePlanRangeDelTL4]
           ,[LinePlanRangeDelAVCO]
           ,[LinePlanRangeDelAVNV]
           ,[LinePlanRangeDelAVN]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[LinePlanFinancialSort]
FROM plmOn30.dbo.pLinePlanRangeAttributeTemp
go

INSERT INTO pLinePlanShowroomStyle
           ([LinePlanShowroomStyleID]
           ,[LinePlanRangeID]
           ,[StyleID]
           ,[CUser]
           ,[CDate])
SELECT [LinePlanShowroomStyleID]
           ,[LinePlanRangeID]
           ,[StyleID]
           ,[CUser]
           ,[CDate]
FROM plmOn30.dbo.pLinePlanShowroomStyle
go


INSERT INTO pLinePlanStyleAttribute
           ([LinePlanStyleAttributeID]
           ,[LinePlanAttributeTypeID]
           ,[LinePlanID]
           ,[AttributeID]
           ,[AttributeName]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate])
SELECT [LinePlanStyleAttributeID]
           ,[LinePlanAttributeTypeID]
           ,[LinePlanID]
           ,[AttributeID]
           ,[AttributeName]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
FROM plmOn30.dbo.pLinePlanStyleAttribute
go


INSERT INTO pLinePlanStyleAttributeItem
           ([LinePlanStyleAttributeItemID]
           ,[LineplanStyleAttributeID]
           ,[LinePlanAttributeTypeID]
           ,[LinePlanID]
           ,[LinePlanAttributeItemID1]
           ,[LinePlanAttributeItemID2]
           ,[LinePlanAttributeItemID3]
           ,[LinePlanAttributeItemID4]
           ,[AttributeID]
           ,[AttributeName]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[LinePlanRangeID])
SELECT [LinePlanStyleAttributeItemID]
           ,[LineplanStyleAttributeID]
           ,[LinePlanAttributeTypeID]
           ,[LinePlanID]
           ,[LinePlanAttributeItemID1]
           ,[LinePlanAttributeItemID2]
           ,[LinePlanAttributeItemID3]
           ,[LinePlanAttributeItemID4]
           ,[AttributeID]
           ,[AttributeName]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[LinePlanRangeID]
FROM plmOn30.dbo.pLinePlanStyleAttributeItem
go

INSERT INTO pLinePlanStyleAttributeType1
           ([AttributeID]
           ,[AttributeName]
           ,[LinePlanAttributeTypeID]
           ,[SAPCode])
SELECT [AttributeID]
           ,[AttributeName]
           ,[LinePlanAttributeTypeID]
           ,[SAPCode]
FROM plmOn30.dbo.pLinePlanStyleAttributeType1
go

INSERT INTO pLinePlanStyleAttributeType2
           ([AttributeID]
           ,[AttributeName]
           ,[LinePlanAttributeTypeID]
           ,[SAPCode])
SELECT [AttributeID]
           ,[AttributeName]
           ,[LinePlanAttributeTypeID]
           ,[SAPCode]
FROM plmOn30.dbo.pLinePlanStyleAttributeType2
go

INSERT INTO pMaterialCoreColor
           ([MaterialCoreColorID]
           ,[MaterialCoreID]
           ,[ColorPaletteID]
           ,[ColorCode]
           ,[ColorName]
           ,[Active]
           ,[Sort]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser])
SELECT [MaterialCoreColorID]
           ,[MaterialCoreID]
           ,[ColorPaletteID]
           ,[ColorCode]
           ,[ColorName]
           ,[Active]
           ,[Sort]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser]
FROM plmOn30.dbo.pMaterialCoreColor
go

INSERT INTO pMaterialCoreColorItem
           ([MaterialCoreColorItemID]
           ,[MaterialCoreColorItemMasterID]
           ,[MaterialCoreColorID]
           ,[MaterialCoreItemID]
           ,[MaterialCoreID]
           ,[MaterialID]
           ,[MaterialColorID]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser]
           ,[MaterialCoreColorItemCopyID])
SELECT [MaterialCoreColorItemID]
           ,[MaterialCoreColorItemMasterID]
           ,[MaterialCoreColorID]
           ,[MaterialCoreItemID]
           ,[MaterialCoreID]
           ,[MaterialID]
           ,[MaterialColorID]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser]
           ,[MaterialCoreColorItemCopyID]
FROM plmOn30.dbo.pMaterialCoreColorItem
go

INSERT INTO pMaterialRequestContent
           ([MaterialContentID]
           ,[MaterialID]
           ,[MaterialTradePartnerID]
           ,[MaterialContentCode]
           ,[MaterialContentPerc]
           ,[MaterialContentName]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser])
SELECT [MaterialContentID]
           ,[MaterialID]
           ,[MaterialTradePartnerID]
           ,[MaterialContentCode]
           ,[MaterialContentPerc]
           ,[MaterialContentName]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser]
FROM plmOn30.dbo.pMaterialRequestContent
go

INSERT INTO pMaterialRequestSubmitGroup
           ([MaterialRequestSubmitGroupID]
           ,[MaterialTradePartnerID]
           ,[MaterialRequestWorkflowID]
           ,[MaterialTradePartnerColorID])
SELECT [MaterialRequestSubmitGroupID]
           ,[MaterialTradePartnerID]
           ,[MaterialRequestWorkflowID]
           ,[MaterialTradePartnerColorID]
FROM plmOn30.dbo.pMaterialRequestSubmitGroup
go

INSERT INTO pMaterialRequestWorkflowGroup
           ([MaterialRequestWorkflowGroupID]
           ,[MaterialRequestWorkflowID]
           ,[MaterialRequestWorkflowGroup]
           ,[MaterialRequestWorkflowGroupSort]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate])
SELECT [MaterialRequestWorkflowGroupID]
           ,[MaterialRequestWorkflowID]
           ,[MaterialRequestWorkflowGroup]
           ,[MaterialRequestWorkflowGroupSort]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
FROM plmOn30.dbo.pMaterialRequestWorkflowGroup
go

INSERT INTO pSampleRequestQASize
           ([SampleRequestQASizeID]
           ,[SampleRequestTradeID]
           ,[SampleRequestWorkflowID]
           ,[SampleWorkflowID]
           ,[WorkflowID]
           ,[StyleID]
           ,[StyleColorID]
           ,[StyleSet]
           ,[SizeRange]
           ,[NumberOfSamples]
           ,[Size0]
           ,[Size1]
           ,[Size2]
           ,[Size3]
           ,[Size4]
           ,[Size5]
           ,[Size6]
           ,[Size7]
           ,[Size8]
           ,[Size9]
           ,[Size10]
           ,[Size11]
           ,[Size12]
           ,[Size13]
           ,[Size14]
           ,[Size15]
           ,[Size16]
           ,[Size17]
           ,[Size18]
           ,[Size19]
           ,[Sel0]
           ,[Sel1]
           ,[Sel2]
           ,[Sel3]
           ,[Sel4]
           ,[Sel5]
           ,[Sel6]
           ,[Sel7]
           ,[Sel8]
           ,[Sel9]
           ,[Sel10]
           ,[Sel11]
           ,[Sel12]
           ,[Sel13]
           ,[Sel14]
           ,[Sel15]
           ,[Sel16]
           ,[Sel17]
           ,[Sel18]
           ,[Sel19]
           ,[Col0]
           ,[Col1]
           ,[Col2]
           ,[Col3]
           ,[Col4]
           ,[Col5]
           ,[Col6]
           ,[Col7]
           ,[Col8]
           ,[Col9]
           ,[Col10]
           ,[Col11]
           ,[Col12]
           ,[Col13]
           ,[Col14]
           ,[Col15]
           ,[Col16]
           ,[Col17]
           ,[Col18]
           ,[Col19]
           ,[MUser]
           ,[MDate]
           ,[FitComment])
SELECT [SampleRequestQASizeID]
           ,[SampleRequestTradeID]
           ,[SampleRequestWorkflowID]
           ,[SampleWorkflowID]
           ,[WorkflowID]
           ,[StyleID]
           ,[StyleColorID]
           ,[StyleSet]
           ,[SizeRange]
           ,[NumberOfSamples]
           ,[Size0]
           ,[Size1]
           ,[Size2]
           ,[Size3]
           ,[Size4]
           ,[Size5]
           ,[Size6]
           ,[Size7]
           ,[Size8]
           ,[Size9]
           ,[Size10]
           ,[Size11]
           ,[Size12]
           ,[Size13]
           ,[Size14]
           ,[Size15]
           ,[Size16]
           ,[Size17]
           ,[Size18]
           ,[Size19]
           ,[Sel0]
           ,[Sel1]
           ,[Sel2]
           ,[Sel3]
           ,[Sel4]
           ,[Sel5]
           ,[Sel6]
           ,[Sel7]
           ,[Sel8]
           ,[Sel9]
           ,[Sel10]
           ,[Sel11]
           ,[Sel12]
           ,[Sel13]
           ,[Sel14]
           ,[Sel15]
           ,[Sel16]
           ,[Sel17]
           ,[Sel18]
           ,[Sel19]
           ,[Col0]
           ,[Col1]
           ,[Col2]
           ,[Col3]
           ,[Col4]
           ,[Col5]
           ,[Col6]
           ,[Col7]
           ,[Col8]
           ,[Col9]
           ,[Col10]
           ,[Col11]
           ,[Col12]
           ,[Col13]
           ,[Col14]
           ,[Col15]
           ,[Col16]
           ,[Col17]
           ,[Col18]
           ,[Col19]
           ,[MUser]
           ,[MDate]
           ,[FitComment]
FROM plmOn30.dbo.pSampleRequestQASize
go

INSERT INTO pSampleRequestQAWorksheet
           ([SampleRequestQAWorksheetID]
           ,[SampleRequestQAWorksheetSizeID]
           ,[SampleRequestTradeID]
           ,[SampleRequestWorkflowID]
           ,[SampleWorkflowID]
           ,[TradePartnerVendorID]
           ,[WorkflowID]
           ,[SpecMasterID]
           ,[POMTempItemID]
           ,[POMLibraryID]
           ,[ModelSpecID]
           ,[ModelID]
           ,[POMTempID]
           ,[StyleID]
           ,[StyleColorID]
           ,[Submit]
           ,[Critical]
           ,[SpecID]
           ,[StyleSet]
           ,[POM]
           ,[PointMeasur]
           ,[TOL]
           ,[TOLN]
           ,[Asked]
           ,[Ask000]
           ,[Ask001]
           ,[Ask002]
           ,[Ask003]
           ,[Ask004]
           ,[Ask005]
           ,[Ask006]
           ,[Ask007]
           ,[Ask008]
           ,[Ask009]
           ,[Ask010]
           ,[Ask011]
           ,[Ask012]
           ,[Ask013]
           ,[Ask014]
           ,[Ask015]
           ,[Ask016]
           ,[Ask017]
           ,[Ask018]
           ,[Ask019]
           ,[Spec000]
           ,[Spec001]
           ,[Spec002]
           ,[Spec003]
           ,[Spec004]
           ,[Spec005]
           ,[Spec006]
           ,[Spec007]
           ,[Spec008]
           ,[Spec009]
           ,[Spec010]
           ,[Spec011]
           ,[Spec012]
           ,[Spec013]
           ,[Spec014]
           ,[Spec015]
           ,[Spec016]
           ,[Spec017]
           ,[Spec018]
           ,[Spec019]
           ,[Spec020]
           ,[Spec021]
           ,[Spec022]
           ,[Spec023]
           ,[Spec024]
           ,[Spec025]
           ,[Spec026]
           ,[Spec027]
           ,[Spec028]
           ,[Spec029]
           ,[Spec030]
           ,[Spec031]
           ,[Spec032]
           ,[Spec033]
           ,[Spec034]
           ,[Spec035]
           ,[Spec036]
           ,[Spec037]
           ,[Spec038]
           ,[Spec039]
           ,[Spec040]
           ,[Spec041]
           ,[Spec042]
           ,[Spec043]
           ,[Spec044]
           ,[Spec045]
           ,[Spec046]
           ,[Spec047]
           ,[Spec048]
           ,[Spec049]
           ,[Spec050]
           ,[Spec051]
           ,[Spec052]
           ,[Spec053]
           ,[Spec054]
           ,[Spec055]
           ,[Spec056]
           ,[Spec057]
           ,[Spec058]
           ,[Spec059]
           ,[Spec060]
           ,[Spec061]
           ,[Spec062]
           ,[Spec063]
           ,[Spec064]
           ,[Spec065]
           ,[Spec066]
           ,[Spec067]
           ,[Spec068]
           ,[Spec069]
           ,[Spec070]
           ,[Spec071]
           ,[Spec072]
           ,[Spec073]
           ,[Spec074]
           ,[Spec075]
           ,[Spec076]
           ,[Spec077]
           ,[Spec078]
           ,[Spec079]
           ,[Spec080]
           ,[Spec081]
           ,[Spec082]
           ,[Spec083]
           ,[Spec084]
           ,[Spec085]
           ,[Spec086]
           ,[Spec087]
           ,[Spec088]
           ,[Spec089]
           ,[Spec090]
           ,[Spec091]
           ,[Spec092]
           ,[Spec093]
           ,[Spec094]
           ,[Spec095]
           ,[Spec096]
           ,[Spec097]
           ,[Spec098]
           ,[Spec099]
           ,[Spec100]
           ,[Spec101]
           ,[Spec102]
           ,[Spec103]
           ,[Spec104]
           ,[Spec105]
           ,[Spec106]
           ,[Spec107]
           ,[Spec108]
           ,[Spec109]
           ,[Spec110]
           ,[Spec111]
           ,[Spec112]
           ,[Spec113]
           ,[Spec114]
           ,[Spec115]
           ,[Spec116]
           ,[Spec117]
           ,[Spec118]
           ,[Spec119]
           ,[Spec120]
           ,[Spec121]
           ,[Spec122]
           ,[Spec123]
           ,[Spec124]
           ,[Spec125]
           ,[Spec126]
           ,[Spec127]
           ,[Spec128]
           ,[Spec129]
           ,[Spec130]
           ,[Spec131]
           ,[Spec132]
           ,[Spec133]
           ,[Spec134]
           ,[Spec135]
           ,[Spec136]
           ,[Spec137]
           ,[Spec138]
           ,[Spec139]
           ,[Spec140]
           ,[Spec141]
           ,[Spec142]
           ,[Spec143]
           ,[Spec144]
           ,[Spec145]
           ,[Spec146]
           ,[Spec147]
           ,[Spec148]
           ,[Spec149]
           ,[Spec150]
           ,[Spec151]
           ,[Spec152]
           ,[Spec153]
           ,[Spec154]
           ,[Spec155]
           ,[Spec156]
           ,[Spec157]
           ,[Spec158]
           ,[Spec159]
           ,[Spec160]
           ,[Spec161]
           ,[Spec162]
           ,[Spec163]
           ,[Spec164]
           ,[Spec165]
           ,[Spec166]
           ,[Spec167]
           ,[Spec168]
           ,[Spec169]
           ,[Spec170]
           ,[Spec171]
           ,[Spec172]
           ,[Spec173]
           ,[Spec174]
           ,[Spec175]
           ,[Spec176]
           ,[Spec177]
           ,[Spec178]
           ,[Spec179]
           ,[Spec180]
           ,[Spec181]
           ,[Spec182]
           ,[Spec183]
           ,[Spec184]
           ,[Spec185]
           ,[Spec186]
           ,[Spec187]
           ,[Spec188]
           ,[Spec189]
           ,[Spec190]
           ,[Spec191]
           ,[Spec192]
           ,[Spec193]
           ,[Spec194]
           ,[Spec195]
           ,[Spec196]
           ,[Spec197]
           ,[Spec198]
           ,[Spec199]
           ,[Spec200]
           ,[Spec201]
           ,[Spec202]
           ,[Spec203]
           ,[Spec204]
           ,[Spec205]
           ,[Spec206]
           ,[Spec207]
           ,[Spec208]
           ,[Spec209]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser]
           ,[Change]
           ,[Sort]
           ,[HowToMeasurText]
           ,[HowToMeasurImage])
SELECT [SampleRequestQAWorksheetID]
           ,[SampleRequestQAWorksheetSizeID]
           ,[SampleRequestTradeID]
           ,[SampleRequestWorkflowID]
           ,[SampleWorkflowID]
           ,[TradePartnerVendorID]
           ,[WorkflowID]
           ,[SpecMasterID]
           ,[POMTempItemID]
           ,[POMLibraryID]
           ,[ModelSpecID]
           ,[ModelID]
           ,[POMTempID]
           ,[StyleID]
           ,[StyleColorID]
           ,[Submit]
           ,[Critical]
           ,[SpecID]
           ,[StyleSet]
           ,[POM]
           ,[PointMeasur]
           ,[TOL]
           ,[TOLN]
           ,[Asked]
           ,[Ask000]
           ,[Ask001]
           ,[Ask002]
           ,[Ask003]
           ,[Ask004]
           ,[Ask005]
           ,[Ask006]
           ,[Ask007]
           ,[Ask008]
           ,[Ask009]
           ,[Ask010]
           ,[Ask011]
           ,[Ask012]
           ,[Ask013]
           ,[Ask014]
           ,[Ask015]
           ,[Ask016]
           ,[Ask017]
           ,[Ask018]
           ,[Ask019]
           ,[Spec000]
           ,[Spec001]
           ,[Spec002]
           ,[Spec003]
           ,[Spec004]
           ,[Spec005]
           ,[Spec006]
           ,[Spec007]
           ,[Spec008]
           ,[Spec009]
           ,[Spec010]
           ,[Spec011]
           ,[Spec012]
           ,[Spec013]
           ,[Spec014]
           ,[Spec015]
           ,[Spec016]
           ,[Spec017]
           ,[Spec018]
           ,[Spec019]
           ,[Spec020]
           ,[Spec021]
           ,[Spec022]
           ,[Spec023]
           ,[Spec024]
           ,[Spec025]
           ,[Spec026]
           ,[Spec027]
           ,[Spec028]
           ,[Spec029]
           ,[Spec030]
           ,[Spec031]
           ,[Spec032]
           ,[Spec033]
           ,[Spec034]
           ,[Spec035]
           ,[Spec036]
           ,[Spec037]
           ,[Spec038]
           ,[Spec039]
           ,[Spec040]
           ,[Spec041]
           ,[Spec042]
           ,[Spec043]
           ,[Spec044]
           ,[Spec045]
           ,[Spec046]
           ,[Spec047]
           ,[Spec048]
           ,[Spec049]
           ,[Spec050]
           ,[Spec051]
           ,[Spec052]
           ,[Spec053]
           ,[Spec054]
           ,[Spec055]
           ,[Spec056]
           ,[Spec057]
           ,[Spec058]
           ,[Spec059]
           ,[Spec060]
           ,[Spec061]
           ,[Spec062]
           ,[Spec063]
           ,[Spec064]
           ,[Spec065]
           ,[Spec066]
           ,[Spec067]
           ,[Spec068]
           ,[Spec069]
           ,[Spec070]
           ,[Spec071]
           ,[Spec072]
           ,[Spec073]
           ,[Spec074]
           ,[Spec075]
           ,[Spec076]
           ,[Spec077]
           ,[Spec078]
           ,[Spec079]
           ,[Spec080]
           ,[Spec081]
           ,[Spec082]
           ,[Spec083]
           ,[Spec084]
           ,[Spec085]
           ,[Spec086]
           ,[Spec087]
           ,[Spec088]
           ,[Spec089]
           ,[Spec090]
           ,[Spec091]
           ,[Spec092]
           ,[Spec093]
           ,[Spec094]
           ,[Spec095]
           ,[Spec096]
           ,[Spec097]
           ,[Spec098]
           ,[Spec099]
           ,[Spec100]
           ,[Spec101]
           ,[Spec102]
           ,[Spec103]
           ,[Spec104]
           ,[Spec105]
           ,[Spec106]
           ,[Spec107]
           ,[Spec108]
           ,[Spec109]
           ,[Spec110]
           ,[Spec111]
           ,[Spec112]
           ,[Spec113]
           ,[Spec114]
           ,[Spec115]
           ,[Spec116]
           ,[Spec117]
           ,[Spec118]
           ,[Spec119]
           ,[Spec120]
           ,[Spec121]
           ,[Spec122]
           ,[Spec123]
           ,[Spec124]
           ,[Spec125]
           ,[Spec126]
           ,[Spec127]
           ,[Spec128]
           ,[Spec129]
           ,[Spec130]
           ,[Spec131]
           ,[Spec132]
           ,[Spec133]
           ,[Spec134]
           ,[Spec135]
           ,[Spec136]
           ,[Spec137]
           ,[Spec138]
           ,[Spec139]
           ,[Spec140]
           ,[Spec141]
           ,[Spec142]
           ,[Spec143]
           ,[Spec144]
           ,[Spec145]
           ,[Spec146]
           ,[Spec147]
           ,[Spec148]
           ,[Spec149]
           ,[Spec150]
           ,[Spec151]
           ,[Spec152]
           ,[Spec153]
           ,[Spec154]
           ,[Spec155]
           ,[Spec156]
           ,[Spec157]
           ,[Spec158]
           ,[Spec159]
           ,[Spec160]
           ,[Spec161]
           ,[Spec162]
           ,[Spec163]
           ,[Spec164]
           ,[Spec165]
           ,[Spec166]
           ,[Spec167]
           ,[Spec168]
           ,[Spec169]
           ,[Spec170]
           ,[Spec171]
           ,[Spec172]
           ,[Spec173]
           ,[Spec174]
           ,[Spec175]
           ,[Spec176]
           ,[Spec177]
           ,[Spec178]
           ,[Spec179]
           ,[Spec180]
           ,[Spec181]
           ,[Spec182]
           ,[Spec183]
           ,[Spec184]
           ,[Spec185]
           ,[Spec186]
           ,[Spec187]
           ,[Spec188]
           ,[Spec189]
           ,[Spec190]
           ,[Spec191]
           ,[Spec192]
           ,[Spec193]
           ,[Spec194]
           ,[Spec195]
           ,[Spec196]
           ,[Spec197]
           ,[Spec198]
           ,[Spec199]
           ,[Spec200]
           ,[Spec201]
           ,[Spec202]
           ,[Spec203]
           ,[Spec204]
           ,[Spec205]
           ,[Spec206]
           ,[Spec207]
           ,[Spec208]
           ,[Spec209]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser]
           ,[Change]
           ,[Sort]
           ,[HowToMeasurText]
           ,[HowToMeasurImage]
FROM plmOn30.dbo.pSampleRequestQAWorkSheet
go

INSERT INTO pStyleActivityType
           ([StyleActivityTypeId]
           ,[StyleActivityTypeName]
           ,[StyleActivityTypeMsg]
           ,[StyleActivityTypeNote])
SELECT [StyleActivityTypeId]
           ,[StyleActivityTypeName]
           ,[StyleActivityTypeMsg]
           ,[StyleActivityTypeNote]
FROM plmOn30.dbo.pStyleActivityType
go

INSERT INTO pStyleColorGroup
           ([StyleColorGroupID]
           ,[StyleID]
           ,[StyleSet]
           ,[ColorGroupID]
           ,[ColorGroupName]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[Sort]
           ,[SizeHomeID]
           ,[SeasonYearID])
SELECT [StyleColorGroupID]
           ,[StyleID]
           ,[StyleSet]
           ,[ColorGroupID]
           ,[ColorGroupName]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[Sort]
           ,[SizeHomeID]
           ,[SeasonYearID]
FROM plmOn30.dbo.pStyleColorGroup
go


INSERT INTO pStyleColorGroupItem
           ([StyleColorGroupItemID]
           ,[StyleColorGroupID]
           ,[StyleColorID]
           ,[StyleID]
           ,[Quantity]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[Sort]
           ,[SizeHomeID]
           ,[SeasonYearID])
SELECT [StyleColorGroupItemID]
           ,[StyleColorGroupID]
           ,[StyleColorID]
           ,[StyleID]
           ,[Quantity]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[Sort]
           ,[SizeHomeID]
           ,[SeasonYearID]
FROM plmOn30.dbo.pStyleColorGroupItem
go

INSERT INTO pStyleColorwaySampleStatus
           ([StatusID]
           ,[Status]
           ,[Active]
           ,[StatusIconUrl]
           ,[Custom])
SELECT [StatusID]
           ,[Status]
           ,[Active]
           ,[StatusIconUrl]
           ,[Custom]
FROM plmOn30.dbo.pStyleColorwaySampleStatus
go

INSERT INTO pStyleColorwayTemp
           ([StyleID]
           ,[NewStyleID]
           ,[StyleColorwayID]
           ,[StyleColorName]
           ,[StyleSeason]
           ,[StyleYear])
SELECT [StyleID]
           ,[NewStyleID]
           ,[StyleColorwayID]
           ,[StyleColorName]
           ,[StyleSeason]
           ,[StyleYear]
FROM plmOn30.dbo.pStyleColorwayTemp
go

INSERT INTO pStyleDevelopmentItemTemp
           ([StyleDevelopmentItemID]
           ,[StyleDevelopmentID]
           ,[NewStyleDevelopmentID]
           ,[StyleID]
           ,[NewStyleID]
           ,[StyleCopyType]
           ,[StyleDevelopmentName]
           ,[Variation]
           ,[DevNo]
           ,[DevTempID]
           ,[DevTempNo]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate])
SELECT [StyleDevelopmentItemID]
           ,[StyleDevelopmentID]
           ,[NewStyleDevelopmentID]
           ,[StyleID]
           ,[NewStyleID]
           ,[StyleCopyType]
           ,[StyleDevelopmentName]
           ,[Variation]
           ,[DevNo]
           ,[DevTempID]
           ,[DevTempNo]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
FROM plmOn30.dbo.pStyleDevelopmentItemTemp
go

INSERT INTO pStyleSourcingColor
           ([StyleSourcingColorID]
           ,[StyleSourcingID]
           ,[StyleColorID]
           ,[MUser]
           ,[MDate]
           ,[ColorCustom1]
           ,[ColorCustom2]
           ,[ColorCustom3])
SELECT [StyleSourcingColorID]
           ,[StyleSourcingID]
           ,[StyleColorID]
           ,[MUser]
           ,[MDate]
           ,[ColorCustom1]
           ,[ColorCustom2]
           ,[ColorCustom3]
FROM plmOn30.dbo.pStyleSourcingColor
go


INSERT INTO sAccessBodyFolder
           ([AccessBodyId]
           ,[BodyTypeId]
           ,[AccessRoleId]
           ,[AccessView]
           ,[AccessCreate]
           ,[AccessModify]
           ,[AccessRemove]
           ,[AccessDelete]
           ,[AccessPrint]
           ,[TeamId]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate])
SELECT [AccessBodyId]
           ,[BodyTypeId]
           ,[AccessRoleId]
           ,[AccessView]
           ,[AccessCreate]
           ,[AccessModify]
           ,[AccessRemove]
           ,[AccessDelete]
           ,[AccessPrint]
           ,[TeamId]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
FROM plmOn30.dbo.sAccessBodyFolder
go


INSERT INTO sAccessGroupBodyFolder
           ([AccessBodyId]
           ,[BodyTypeId]
           ,[AccessRoleId]
           ,[AccessView]
           ,[AccessCreate]
           ,[AccessRemove]
           ,[AccessModify]
           ,[AccessDelete]
           ,[AccessPrint]
           ,[GroupID]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate])
SELECT [AccessBodyId]
           ,[BodyTypeId]
           ,[AccessRoleId]
           ,[AccessView]
           ,[AccessCreate]
           ,[AccessRemove]
           ,[AccessModify]
           ,[AccessDelete]
           ,[AccessPrint]
           ,[GroupID]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
FROM plmOn30.dbo.sAccessGroupBodyFolder
go

INSERT INTO sOverrideSPX
           ([OriginalSPX]
           ,[FormName]
           ,[Override])
SELECT [OriginalSPX]
           ,[FormName]
           ,[Override]
FROM plmOn30.dbo.sOverrideSPX
go


INSERT INTO sOverrideVWX
           ([OriginalVWX]
           ,[FormName]
           ,[Override])
SELECT [OriginalVWX]
           ,[FormName]
           ,[Override]
FROM plmOn30.dbo.sOverrideVWX
go


INSERT INTO sServiceQueue
           ([ServiceQueueSql]
           ,[ServiceQueuePriority]
           ,[ServiceQueueDate])
SELECT [ServiceQueueSql]
           ,[ServiceQueuePriority]
           ,[ServiceQueueDate]
FROM plmOn30.dbo.sServiceQueue
go

INSERT INTO sServiceQueueRunning
           ([ServiceQueueID]
           ,[ServiceQueueSql]
           ,[ServiceQueuePriority]
           ,[ServiceQueueRunningDate]
           ,[Attempt])
SELECT [ServiceQueueID]
           ,[ServiceQueueSql]
           ,[ServiceQueuePriority]
           ,[ServiceQueueRunningDate]
           ,[Attempt]
FROM plmOn30.dbo.sServiceQueueRunning
go

INSERT INTO sSystemButtons
           ([SystemButtonID]
           ,[ButtonIcon]
           ,[ButtonType]
           ,[DesignString]
           ,[da_DK]
           ,[de_DE]
           ,[en_US]
           ,[en_GB]
           ,[en_CA]
           ,[fr_FR]
           ,[fr_CA]
           ,[es_ES]
           ,[es_MX]
           ,[hi_IN]
           ,[it_IT]
           ,[ja_JA]
           ,[ko_KR]
           ,[nl_NL]
           ,[pl_PL]
           ,[pt_PT]
           ,[pt_BR]
           ,[ru_RU]
           ,[sv_FI]
           ,[sv_SE]
           ,[tr_TR]
           ,[zh_CHS]
           ,[zh_CHT]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser])
SELECT [SystemButtonID]
           ,[ButtonIcon]
           ,[ButtonType]
           ,[DesignString]
           ,[da_DK]
           ,[de_DE]
           ,[en_US]
           ,[en_GB]
           ,[en_CA]
           ,[fr_FR]
           ,[fr_CA]
           ,[es_ES]
           ,[es_MX]
           ,[hi_IN]
           ,[it_IT]
           ,[ja_JA]
           ,[ko_KR]
           ,[nl_NL]
           ,[pl_PL]
           ,[pt_PT]
           ,[pt_BR]
           ,[ru_RU]
           ,[sv_FI]
           ,[sv_SE]
           ,[tr_TR]
           ,[zh_CHS]
           ,[zh_CHT]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser]
FROM plmOn30.dbo.sSystemButtons
go


INSERT INTO sSystemCulture
           ([CultureIndentifierID]
           ,[CultureName]
           ,[CultureCountry]
           ,[CultureLanguage]
           ,[Active]
           ,[Unicode])
SELECT [CultureIndentifierID]
           ,[CultureName]
           ,[CultureCountry]
           ,[CultureLanguage]
           ,[Active]
           ,[Unicode]
FROM plmOn30.dbo.sSystemCulture
go

INSERT INTO sSystemPageStrings
           ([sSystemPageString]
           ,[FormName]
           ,[SystemStringID]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser])
SELECT [sSystemPageString]
           ,[FormName]
           ,[SystemStringID]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser]
FROM plmOn30.dbo.sSystemPageStrings
go

INSERT INTO sSystemStrings
           ([SystemStringID]
           ,[DesignString]
           ,[da_DK]
           ,[de_DE]
           ,[en_US]
           ,[en_GB]
           ,[en_CA]
           ,[fr_FR]
           ,[fr_CA]
           ,[es_ES]
           ,[es_MX]
           ,[hi_IN]
           ,[it_IT]
           ,[ja_JA]
           ,[ko_KR]
           ,[nl_NL]
           ,[pl_PL]
           ,[pt_PT]
           ,[pt_BR]
           ,[ru_RU]
           ,[sv_FI]
           ,[sv_SE]
           ,[tr_TR]
           ,[zh_CHS]
           ,[zh_CHT]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser])
SELECT [SystemStringID]
           ,[DesignString]
           ,[da_DK]
           ,[de_DE]
           ,[en_US]
           ,[en_GB]
           ,[en_CA]
           ,[fr_FR]
           ,[fr_CA]
           ,[es_ES]
           ,[es_MX]
           ,[hi_IN]
           ,[it_IT]
           ,[ja_JA]
           ,[ko_KR]
           ,[nl_NL]
           ,[pl_PL]
           ,[pt_PT]
           ,[pt_BR]
           ,[ru_RU]
           ,[sv_FI]
           ,[sv_SE]
           ,[tr_TR]
           ,[zh_CHS]
           ,[zh_CHT]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser]
FROM plmOn30.dbo.sSystemStrings
go

INSERT INTO sTempSequentialId
           ([SequentialId]
           ,[SequentialNo])
SELECT [SequentialId]
           ,[SequentialNo]
FROM plmOn30.dbo.sTempSequentialId
go

INSERT INTO sUserStrings
           ([UserStringID]
           ,[DesignString]
           ,[da_DK]
           ,[de_DE]
           ,[en_US]
           ,[en_GB]
           ,[en_CA]
           ,[fr_FR]
           ,[fr_CA]
           ,[es_ES]
           ,[es_MX]
           ,[hi_IN]
           ,[it_IT]
           ,[ja_JA]
           ,[ko_KR]
           ,[nl_NL]
           ,[pl_PL]
           ,[pt_PT]
           ,[pt_BR]
           ,[ru_RU]
           ,[sv_FI]
           ,[sv_SE]
           ,[tr_TR]
           ,[zh_CHS]
           ,[zh_CHT]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser])
SELECT [UserStringID]
           ,[DesignString]
           ,[da_DK]
           ,[de_DE]
           ,[en_US]
           ,[en_GB]
           ,[en_CA]
           ,[fr_FR]
           ,[fr_CA]
           ,[es_ES]
           ,[es_MX]
           ,[hi_IN]
           ,[it_IT]
           ,[ja_JA]
           ,[ko_KR]
           ,[nl_NL]
           ,[pl_PL]
           ,[pt_PT]
           ,[pt_BR]
           ,[ru_RU]
           ,[sv_FI]
           ,[sv_SE]
           ,[tr_TR]
           ,[zh_CHS]
           ,[zh_CHT]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser]
FROM plmOn30.dbo.sUserStrings
go

INSERT INTO sUserXMLStrings
           ([UserXMLStringID]
           ,[XMLName]
           ,[UserStringID]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser])
SELECT [UserXMLStringID]
           ,[XMLName]
           ,[UserStringID]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser]
FROM plmOn30.dbo.sUserXMLStrings
go


INSERT INTO sVersion
           ([AppName]
           ,[Version]
           ,[LastScriptRun]
           ,[TimeStamp])
SELECT [AppName]
           ,[Version]
           ,[LastScriptRun]
           ,[TimeStamp]
FROM plmOn30.dbo.sVersion
go


INSERT INTO xCustom26
           ([Custom]
           ,[CustomKey]
           ,[Custom1]
           ,[Active]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[CustomID]
           ,[CustomSort])
SELECT [Custom]
           ,[CustomKey]
           ,[Custom1]
           ,[Active]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[CustomID]
           ,[CustomSort]
FROM plmOn30.dbo.XCustom26
go


INSERT INTO xCustom28
           ([Custom]
           ,[CustomKey]
           ,[Custom1]
           ,[Active]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[CustomID]
           ,[CustomSort])
SELECT [Custom]
           ,[CustomKey]
           ,[Custom1]
           ,[Active]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[CustomID]
           ,[CustomSort]
FROM plmOn30.dbo.XCustom28
go

INSERT INTO xCustom29
           ([Custom]
           ,[CustomKey]
           ,[Custom1]
           ,[Active]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[CustomID]
           ,[CustomSort])
SELECT [Custom]
           ,[CustomKey]
           ,[Custom1]
           ,[Active]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[CustomID]
           ,[CustomSort]
FROM plmOn30.dbo.XCustom29
go


INSERT INTO xCustom55
           ([Custom]
           ,[CustomKey]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[Active]
           ,[Custom1]
           ,[SAPCode]
           ,[CustomID]
           ,[CustomSort])
SELECT [Custom]
           ,[CustomKey]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[Active]
           ,[Custom1]
           ,[SAPCode]
           ,[CustomID]
           ,[CustomSort]
FROM plmOn30.dbo.XCustom55
go

INSERT INTO xCustom99
           ([CustomID]
           ,[Custom]
           ,[CustomKey]
           ,[Custom1]
           ,[Active]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[CustomSort])
SELECT [CustomID]
           ,[Custom]
           ,[CustomKey]
           ,[Custom1]
           ,[Active]
           ,[CUser]
           ,[CDate]
           ,[MUser]
           ,[MDate]
           ,[CustomSort]
FROM plmOn30.dbo.XCustom99
go


INSERT INTO rDashFolder
           ([DashFolderID]
           ,[DashFolderName]
           ,[DashFolderSort]
           ,[DashFolderActive])
SELECT [DashFolderID]
           ,[DashFolderName]
           ,[DashFolderSort]
           ,[DashFolderActive]
FROM plmOn30.dbo.rDashFolder
go

INSERT INTO rDashFolderItem
           ([DashFolderItemID]
           ,[DashFolderID]
           ,[DashFolderItemName]
           ,[DashFolderItemUrl]
           ,[DashFolderItemIcon]
           ,[DashFolderItemSort]
           ,[DashFolderItemActive])
SELECT [DashFolderItemID]
           ,[DashFolderID]
           ,[DashFolderItemName]
           ,[DashFolderItemUrl]
           ,[DashFolderItemIcon]
           ,[DashFolderItemSort]
           ,[DashFolderItemActive]
FROM plmOn30.dbo.rDashFolderItem
go


INSERT INTO rReportMaterialHeaderTemp
           ([DataXmlId]
           ,[DataColumnNumber]
           ,[DataColumnName]
           ,[DataHeader]
           ,[DataValue]
           ,[DataSort]
           ,[CDate])
SELECT [DataXmlId]
           ,[DataColumnNumber]
           ,[DataColumnName]
           ,[DataHeader]
           ,[DataValue]
           ,[DataSort]
           ,[CDate]
FROM plmOn30.dbo.rReportMaterialHeaderTemp
go

INSERT INTO rReportMaterialRequestItemTemp
           ([DataXmlId]
           ,[MaterialRequestSubmitItemID]
           ,[MaterialRequestSubmitID]
           ,[DataColumnNumber]
           ,[DataColumnName]
           ,[DataColumnValue]
           ,[DataSort]
           ,[CDate])
SELECT DataXmlId
           ,[MaterialRequestSubmitItemID]
           ,[MaterialRequestSubmitID]
           ,[DataColumnNumber]
           ,[DataColumnName]
           ,[DataColumnValue]
           ,[DataSort]
           ,[CDate]
FROM plmOn30.dbo.rReportMaterialRequestItemTemp
go


INSERT INTO rReportMaterialRequestSubmitFolder
           ([ReportMaterialRequestSubmitFolderID]
           ,[ReportMaterialRequestSubmitName]
           ,[ReportMaterialRequestSubmitFormName]
           ,[ReportMaterialRequestSubmitGroup]
           ,[ReportMaterialRequestSubmitFinal]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser]
           ,[ReportMaterialRequestSubmitSort]
           ,[Active]
           ,[srmOn])
SELECT [ReportMaterialRequestSubmitFolderID]
           ,[ReportMaterialRequestSubmitName]
           ,[ReportMaterialRequestSubmitFormName]
           ,[ReportMaterialRequestSubmitGroup]
           ,[ReportMaterialRequestSubmitFinal]
           ,[CDate]
           ,[CUser]
           ,[MDate]
           ,[MUser]
           ,[ReportMaterialRequestSubmitSort]
           ,[Active]
           ,[srmOn]
FROM plmOn30.dbo.rReportMaterialRequestSubmitFolder
go

INSERT INTO rReportMaterialRequestSubmitItem
           ([ReportMaterialRequestSubmitPageID]
           ,[ReportMaterialRequestSubmitFolderID]
           ,[ReportPageTypeID]
           ,[ReportTemplateName]
           ,[ReportPageName]
           ,[ReportPageDescription]
           ,[ReportServerType]
           ,[ReportFormName]
           ,[ReportPageURL]
           ,[ReportPKIField]
           ,[ReportPageActive]
           ,[ReportPageFormat]
           ,[ReportPageApproved]
           ,[ReportPageSort])
SELECT [ReportMaterialRequestSubmitPageID]
           ,[ReportMaterialRequestSubmitFolderID]
           ,[ReportPageTypeID]
           ,[ReportTemplateName]
           ,[ReportPageName]
           ,[ReportPageDescription]
           ,[ReportServerType]
           ,[ReportFormName]
           ,[ReportPageURL]
           ,[ReportPKIField]
           ,[ReportPageActive]
           ,[ReportPageFormat]
           ,[ReportPageApproved]
           ,[ReportPageSort]
FROM plmOn30.dbo.rReportMaterialRequestSubmitItem
go

INSERT INTO rReportSrmFolder
           ([ReportSrmFolderID]
           ,[ReportSrmFolderName]
           ,[ReportSrmFolderSort]
           ,[ReportSrmFolderActive])
SELECT [ReportSrmFolderID]
           ,[ReportSrmFolderName]
           ,[ReportSrmFolderSort]
           ,[ReportSrmFolderActive]
FROM plmOn30.dbo.rReportSrmFolder
go

INSERT INTO rReportSrmFolderItem
           ([ReportSrmFolderItemID]
           ,[ReportSrmFolderID]
           ,[ReportSrmFolderItemName]
           ,[ReportSrmFolderItemUrl]
           ,[ReportSrmFolderItemIcon]
           ,[ReportSrmFolderItemSort]
           ,[ReportSrmFolderItemActive])
SELECT [ReportSrmFolderItemID]
           ,[ReportSrmFolderID]
           ,[ReportSrmFolderItemName]
           ,[ReportSrmFolderItemUrl]
           ,[ReportSrmFolderItemIcon]
           ,[ReportSrmFolderItemSort]
           ,[ReportSrmFolderItemActive]
FROM plmOn30.dbo.rReportSrmFolderItem
go
